
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mws_a
 */
public class AddDepartmentOfficer extends javax.swing.JFrame {

    /**
     * Creates new form AddDepartmentOfficer
     */
    private String username;
    private String password;
    
    public AddDepartmentOfficer(String username, String password) {
        initComponents();
        setUsername(username);
        setPassword(password);
    }
    
    //    Setters
    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    

//   getters
    public String getUsername() {
        return this.username;
    }
    
    public String getPassword() {
        return this.password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_first_name = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_last_name = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_nic = new javax.swing.JLabel();
        lbl_dob = new javax.swing.JLabel();
        txt_first_name = new javax.swing.JTextField();
        txt_last_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        txt_email = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        dtch_dob = new com.toedter.calendar.JDateChooser();
        lbl_error_message = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_instructions2 = new javax.swing.JLabel();
        lbl_instructions3 = new javax.swing.JLabel();
        lbl_instructions = new javax.swing.JLabel();
        lbl_instructions1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(830, 550));

        lbl_first_name.setBackground(new java.awt.Color(248, 249, 250));
        lbl_first_name.setLayout(null);

        lbl_title.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_title.setText("First Name");
        lbl_first_name.add(lbl_title);
        lbl_title.setBounds(20, 160, 110, 40);

        jLabel1.setBackground(new java.awt.Color(33, 37, 41));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 249, 250));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jLabel1.setText("Addd Department Officer");
        jLabel1.setOpaque(true);
        lbl_first_name.add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 110);

        lbl_last_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_last_name.setText("Last Name");
        lbl_first_name.add(lbl_last_name);
        lbl_last_name.setBounds(20, 210, 120, 40);

        lbl_address.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_address.setText("Address");
        lbl_first_name.add(lbl_address);
        lbl_address.setBounds(20, 290, 110, 40);

        lbl_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_email.setText("Email");
        lbl_first_name.add(lbl_email);
        lbl_email.setBounds(20, 360, 110, 40);

        lbl_nic.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_nic.setText("NIC");
        lbl_first_name.add(lbl_nic);
        lbl_nic.setBounds(20, 460, 120, 40);

        lbl_dob.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_dob.setText("Date of Birth");
        lbl_first_name.add(lbl_dob);
        lbl_dob.setBounds(20, 410, 110, 40);

        txt_first_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_first_name.add(txt_first_name);
        txt_first_name.setBounds(130, 160, 230, 40);

        txt_last_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_first_name.add(txt_last_name);
        txt_last_name.setBounds(130, 210, 230, 40);

        txt_address.setColumns(20);
        txt_address.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_address.setRows(5);
        jScrollPane1.setViewportView(txt_address);

        lbl_first_name.add(jScrollPane1);
        jScrollPane1.setBounds(130, 260, 230, 90);

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_first_name.add(txt_email);
        txt_email.setBounds(130, 360, 230, 40);

        txt_nic.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_first_name.add(txt_nic);
        txt_nic.setBounds(130, 460, 230, 40);

        dtch_dob.setDateFormatString("yyyy-MM-dd");
        lbl_first_name.add(dtch_dob);
        dtch_dob.setBounds(130, 410, 230, 40);

        lbl_error_message.setForeground(new java.awt.Color(255, 0, 0));
        lbl_first_name.add(lbl_error_message);
        lbl_error_message.setBounds(20, 630, 780, 40);

        btn_add.setBackground(new java.awt.Color(33, 37, 41));
        btn_add.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_add.setForeground(new java.awt.Color(248, 249, 250));
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        lbl_first_name.add(btn_add);
        btn_add.setBounds(250, 550, 100, 50);

        btn_clear.setBackground(new java.awt.Color(33, 37, 41));
        btn_clear.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(248, 249, 250));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        lbl_first_name.add(btn_clear);
        btn_clear.setBounds(140, 550, 100, 50);

        btn_close.setBackground(new java.awt.Color(33, 37, 41));
        btn_close.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_close.setForeground(new java.awt.Color(248, 249, 250));
        btn_close.setText("Back");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        lbl_first_name.add(btn_close);
        btn_close.setBounds(30, 550, 100, 50);

        jPanel1.setBackground(new java.awt.Color(248, 249, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instructions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(51, 55, 65))); // NOI18N
        jPanel1.setLayout(null);

        lbl_instructions2.setText("NIC should not exist in the WCMS either.");
        jPanel1.add(lbl_instructions2);
        lbl_instructions2.setBounds(10, 150, 300, 40);

        lbl_instructions3.setText("Email should be correctly formatted and cannot exist in WCMS database.");
        jPanel1.add(lbl_instructions3);
        lbl_instructions3.setBounds(10, 110, 400, 40);

        lbl_instructions.setText("Names should be something other than First Lame and Last Lame.");
        jPanel1.add(lbl_instructions);
        lbl_instructions.setBounds(10, 70, 380, 40);

        lbl_instructions1.setText("Make sure that you filled all fields.");
        jPanel1.add(lbl_instructions1);
        lbl_instructions1.setBounds(10, 20, 250, 50);

        lbl_first_name.add(jPanel1);
        jPanel1.setBounds(390, 160, 420, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_first_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_first_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        lbl_error_message.setText("");
        
        if (txt_first_name.getText().equals("First Name") || 
                txt_first_name.getText().equals("") ||
                txt_last_name.getText().equals("Last Name") ||
                txt_last_name.getText().equals("") ||
                txt_address.getText().equals("") ||
                dtch_dob.getDate() == null ||
                txt_email.getText().equals("") ||
                !Validator.validateEmailFormat(txt_email.getText()) ||
                Validator.validateEmail(txt_email.getText()) ||
                txt_nic.getText().equals("") ||
                Validator.validateNic(txt_nic.getText())                  
                ) {
            lbl_error_message.setText("You must enter valid values in the fields! Refer to the instructions in the form.");
        } else {
//            Setting up dob in an acceptable format
            Date dob = dtch_dob.getDate();
            SimpleDateFormat formatter = new SimpleDateFormat("YYYY-MM-d");
            String dob_mysql_date_string = formatter.format(dob);
            int dob_year = Integer.parseInt(dob_mysql_date_string.substring(0,4));
            int dob_month = Integer.parseInt(dob_mysql_date_string.substring(5,7));
            int dob_day = Integer.parseInt(dob_mysql_date_string.substring(8));
            
            SystemAdministrator sa = new SystemAdministrator();
            sa.setUsername(getUsername());
            sa.setPassword(getPassword());
            String message = sa.registerDepartmentOfficer(txt_first_name.getText(), 
                    txt_last_name.getText(), 
                    txt_address.getText(), 
                    LocalDate.of(dob_year, dob_month, dob_day), 
                    txt_email.getText(), 
                    txt_nic.getText());

            JOptionPane.showMessageDialog(this, "Department Officer Successfully!. Your information: " + message);
            SystemAdministratorDashboard sad = new SystemAdministratorDashboard(getUsername(), getPassword());
            sad.setVisible(true);
            dispose();
//            
           
                   
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:        
        txt_first_name.setText("");
        txt_last_name.setText("");
        txt_address.setText("");
        dtch_dob.setDate(null);
        txt_email.setText("");
        txt_nic.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        SystemAdministratorDashboard sad = new SystemAdministratorDashboard(getUsername(), getPassword());
        sad.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddDepartmentOfficer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddDepartmentOfficer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddDepartmentOfficer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddDepartmentOfficer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddDepartmentOfficer("Admin", "cypher").setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_close;
    private com.toedter.calendar.JDateChooser dtch_dob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_dob;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_error_message;
    private javax.swing.JPanel lbl_first_name;
    private javax.swing.JLabel lbl_instructions;
    private javax.swing.JLabel lbl_instructions1;
    private javax.swing.JLabel lbl_instructions2;
    private javax.swing.JLabel lbl_instructions3;
    private javax.swing.JLabel lbl_last_name;
    private javax.swing.JLabel lbl_nic;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_first_name;
    private javax.swing.JTextField txt_last_name;
    private javax.swing.JTextField txt_nic;
    // End of variables declaration//GEN-END:variables
}
