
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mws_a
 */
public class AddElephantLocationForm extends javax.swing.JFrame {

    /**
     * Creates new form AddElephantLocationForm
     */
    private String rangerId; 
    private String wpa;
    private String username;
    private String password;
    
    public AddElephantLocationForm(String rangerId, String wpa, String username, String password) {
        initComponents();
        setRangerId(rangerId);
        setWpa(wpa);
        setUsername(username);
        setPassword(password);
        populateElephantCmb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_latitude = new javax.swing.JLabel();
        lbl_longitude = new javax.swing.JLabel();
        txt_latitude = new javax.swing.JTextField();
        txt_longitude = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        lbl_elephant = new javax.swing.JLabel();
        cmbElephant = new javax.swing.JComboBox<>();
        lbl_error_message = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_instructions5 = new javax.swing.JLabel();
        lbl_instructions6 = new javax.swing.JLabel();
        lbl_instructions7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        lbl_title.setBackground(new java.awt.Color(33, 37, 41));
        lbl_title.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        lbl_title.setText("Add Elephant Location");
        lbl_title.setOpaque(true);
        jPanel1.add(lbl_title);
        lbl_title.setBounds(-10, 0, 840, 100);

        lbl_latitude.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_latitude.setText("Latitude");
        jPanel1.add(lbl_latitude);
        lbl_latitude.setBounds(10, 190, 120, 40);

        lbl_longitude.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_longitude.setText("Longitude");
        jPanel1.add(lbl_longitude);
        lbl_longitude.setBounds(10, 240, 110, 40);

        txt_latitude.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_latitude);
        txt_latitude.setBounds(110, 190, 300, 40);

        txt_longitude.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_longitude);
        txt_longitude.setBounds(110, 240, 300, 40);

        btn_add.setBackground(new java.awt.Color(33, 37, 41));
        btn_add.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_add.setForeground(new java.awt.Color(248, 249, 250));
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add);
        btn_add.setBounds(300, 310, 100, 40);

        lbl_elephant.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_elephant.setText("Elephant");
        jPanel1.add(lbl_elephant);
        lbl_elephant.setBounds(10, 140, 120, 40);

        cmbElephant.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbElephant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jPanel1.add(cmbElephant);
        cmbElephant.setBounds(110, 140, 300, 40);

        lbl_error_message.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_error_message.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_error_message);
        lbl_error_message.setBounds(10, 430, 400, 50);

        btn_back.setBackground(new java.awt.Color(33, 37, 41));
        btn_back.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_back.setForeground(new java.awt.Color(248, 249, 250));
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(200, 310, 90, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instructions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(33, 37, 41))); // NOI18N

        lbl_instructions5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instructions5.setText("All fields must be filled");
        lbl_instructions5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_instructions6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instructions6.setText("Lattitude and longitude must be numbers ");
        lbl_instructions6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_instructions7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instructions7.setText("Elephant id should be picked and it cannot be Select");
        lbl_instructions7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_instructions5, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbl_instructions7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                        .addComponent(lbl_instructions6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(479, 479, 479))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_instructions5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_instructions6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lbl_instructions7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(450, 140, 370, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        lbl_error_message.setText("");
        if (txt_latitude.getText().equals("") ||
                !Validator.isNumber(txt_latitude.getText()) ||
                txt_longitude.getText().equals("") || 
                !Validator.isNumber(txt_longitude.getText()) ||
                String.valueOf(cmbElephant.getSelectedItem()).equals("Select")) {
            lbl_error_message.setText("Refer to the instructions and insert valid vlues");
        } else {
            ElephantLocation el = new ElephantLocation();
            el.setGeographic_coordinates(txt_latitude.getText() + ", " + txt_longitude.getText());
            el.setElephant(String.valueOf(cmbElephant.getSelectedItem()));
            el.setTime(String.valueOf(LocalDateTime.now()));
            el.add(); 
            JOptionPane.showMessageDialog(this,"Elephant location is added successfully.");  
            WildlifeRangerDashboard wrd = new WildlifeRangerDashboard(getRangerId(),getUsername(), getPassword(), "Wildlife Ranger");
            wrd.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        WildlifeRangerDashboard wrd = new WildlifeRangerDashboard(getRangerId(), "xx", "xx", "xx");
        wrd.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    
//    Setters
    public void setRangerId(String rangerId) {

        this.rangerId = rangerId;
    }

    public void setWpa(String wpa) {
        this.wpa = wpa;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
//    Getters

    public String getRangerId() {
        return rangerId;
    }

    public String getWpa() {
        return wpa;
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }
    
//    Other methods
    
    private void populateElephantCmb() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT id FROM elephant";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            System.out.println("WPA: " + getWpa());

            while (rs.next()) {
                cmbElephant.addItem(rs.getString("id"));
            } 

            conn.close();
        } catch (Exception e) {
            lbl_error_message.setText("Failiure: " + e);
            System.out.println("Failiure: " + e);
        }
    }
    
    

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//        */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddElephantLocationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddElephantLocationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddElephantLocationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddElephantLocationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddElephantLocationForm("87","11").setVisible(true);
//            }
//        });
//    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_back;
    private javax.swing.JComboBox<String> cmbElephant;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_elephant;
    private javax.swing.JLabel lbl_error_message;
    private javax.swing.JLabel lbl_instructions5;
    private javax.swing.JLabel lbl_instructions6;
    private javax.swing.JLabel lbl_instructions7;
    private javax.swing.JLabel lbl_latitude;
    private javax.swing.JLabel lbl_longitude;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_latitude;
    private javax.swing.JTextField txt_longitude;
    // End of variables declaration//GEN-END:variables
}
