
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mws_a
 */
public class AlterDepartmentOfficerForm extends javax.swing.JFrame {

    /**
     * Creates new form AlterDepartmentOfficerForm
     */
    private String username;
    private String password;
    
//    Editing Department officer properties
    private String do_username;
    private String do_password;
    
    public AlterDepartmentOfficerForm(String username, String password) {
        initComponents();
        populatecmbDoId();
    }
    
//    Setters

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setDo_username(String do_username) {
        this.do_username = do_username;
    }

    public void setDo_password(String do_password) {
        this.do_password = do_password;
    }
    
    
    
//    Getters

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }

    public String getDo_username() {
        return do_username;
    }

    public String getDo_password() {
        return do_password;
    }
    
    
    
    
    
//    Other methods
    private void populatecmbDoId () {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT id FROM user WHERE role = 'Department Officer'";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                cmb_department_officer__id.addItem(rs.getString("id"));
            } 

            conn.close();
        } catch (Exception e) {
            lbl_error_message.setText("Failiure: " + e);
            System.out.println("Failiure: " + e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_department_officer_id = new javax.swing.JLabel();
        cmb_department_officer__id = new javax.swing.JComboBox<>();
        lbl_title1 = new javax.swing.JLabel();
        txt_first_name = new javax.swing.JTextField();
        txt_last_name = new javax.swing.JTextField();
        lbl_last_name = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        txt_email = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        lbl_dob = new javax.swing.JLabel();
        dtch_dob = new com.toedter.calendar.JDateChooser();
        txt_nic = new javax.swing.JTextField();
        lbl_nic = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        lbl_error_message = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_instructions2 = new javax.swing.JLabel();
        lbl_instructions3 = new javax.swing.JLabel();
        lbl_instructions = new javax.swing.JLabel();
        lbl_instructions1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 249, 250));
        jPanel1.setLayout(null);

        lbl_title.setBackground(new java.awt.Color(33, 37, 41));
        lbl_title.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        lbl_title.setText("Department Officer Alter Form");
        lbl_title.setOpaque(true);
        jPanel1.add(lbl_title);
        lbl_title.setBounds(2, 13, 1000, 100);

        lbl_department_officer_id.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_department_officer_id.setText("ID");
        jPanel1.add(lbl_department_officer_id);
        lbl_department_officer_id.setBounds(30, 180, 100, 40);

        cmb_department_officer__id.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmb_department_officer__id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cmb_department_officer__id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_department_officer__idItemStateChanged(evt);
            }
        });
        jPanel1.add(cmb_department_officer__id);
        cmb_department_officer__id.setBounds(130, 180, 130, 40);

        lbl_title1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_title1.setText("First Name");
        jPanel1.add(lbl_title1);
        lbl_title1.setBounds(30, 230, 100, 40);

        txt_first_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_first_name);
        txt_first_name.setBounds(130, 230, 230, 40);

        txt_last_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_last_name);
        txt_last_name.setBounds(130, 280, 230, 40);

        lbl_last_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_last_name.setText("Last Name");
        jPanel1.add(lbl_last_name);
        lbl_last_name.setBounds(30, 280, 100, 40);

        lbl_address.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_address.setText("Address");
        jPanel1.add(lbl_address);
        lbl_address.setBounds(30, 350, 100, 40);

        txt_address.setColumns(20);
        txt_address.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_address.setRows(5);
        jScrollPane1.setViewportView(txt_address);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(130, 330, 230, 116);

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_email);
        txt_email.setBounds(130, 430, 230, 40);

        lbl_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_email.setText("Email");
        jPanel1.add(lbl_email);
        lbl_email.setBounds(30, 430, 100, 40);

        lbl_dob.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_dob.setText("Date of Birth");
        jPanel1.add(lbl_dob);
        lbl_dob.setBounds(30, 480, 120, 40);

        dtch_dob.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dtch_dob);
        dtch_dob.setBounds(130, 480, 230, 40);

        txt_nic.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_nic);
        txt_nic.setBounds(130, 530, 230, 40);

        lbl_nic.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_nic.setText("NIC");
        jPanel1.add(lbl_nic);
        lbl_nic.setBounds(30, 530, 110, 40);

        btn_close.setBackground(new java.awt.Color(33, 37, 41));
        btn_close.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_close.setForeground(new java.awt.Color(248, 249, 250));
        btn_close.setText("Back");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_close);
        btn_close.setBounds(20, 590, 110, 60);

        btn_clear.setBackground(new java.awt.Color(33, 37, 41));
        btn_clear.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(248, 249, 250));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear);
        btn_clear.setBounds(140, 590, 110, 60);

        btn_edit.setBackground(new java.awt.Color(33, 37, 41));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(248, 249, 250));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit);
        btn_edit.setBounds(380, 590, 110, 60);

        lbl_error_message.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_error_message);
        lbl_error_message.setBounds(10, 670, 820, 50);

        btn_delete.setBackground(new java.awt.Color(33, 37, 41));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(248, 249, 250));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);
        btn_delete.setBounds(260, 590, 110, 60);

        jPanel2.setBackground(new java.awt.Color(248, 249, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instructions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(33, 37, 41))); // NOI18N
        jPanel2.setLayout(null);

        lbl_instructions2.setText("NIC should not exist in the WCMS either.");
        jPanel2.add(lbl_instructions2);
        lbl_instructions2.setBounds(20, 140, 300, 40);

        lbl_instructions3.setText("Email should be correctly formatted and cannot exist in WCMS database.");
        jPanel2.add(lbl_instructions3);
        lbl_instructions3.setBounds(20, 100, 400, 40);

        lbl_instructions.setText("Names should be something other than First Lame and Last Lame.");
        jPanel2.add(lbl_instructions);
        lbl_instructions.setBounds(20, 60, 380, 40);

        lbl_instructions1.setText("Make sure that you filled all fields.");
        jPanel2.add(lbl_instructions1);
        lbl_instructions1.setBounds(20, 10, 250, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(400, 180, 440, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        SystemAdministratorDashboard sad = new SystemAdministratorDashboard(getUsername(), getPassword());
        sad.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        cmb_department_officer__id.setSelectedItem("Select");
        txt_first_name.setText("");
        txt_last_name.setText("");
        txt_address.setText("");
        dtch_dob.setDate(null);
        txt_email.setText("");
        txt_nic.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        lbl_error_message.setText("");

        if (txt_first_name.getText().equals("First Name") ||
            txt_first_name.getText().equals("") ||
            txt_last_name.getText().equals("Last Name") ||
            txt_last_name.getText().equals("") ||
            txt_address.getText().equals("") ||
            dtch_dob.getDate() == null ||
            txt_email.getText().equals("") ||
            !Validator.validateEmailFormat(txt_email.getText()) ||
            txt_nic.getText().equals("") 
        ) {
            lbl_error_message.setText("You must enter valid values in the fields by Refering to the instructions in the form.");
        } else {
            //            Setting up dob in an acceptable format
            Date dob = dtch_dob.getDate();
            SimpleDateFormat formatter = new SimpleDateFormat("YYYY-MM-d");
            String dob_mysql_date_string = formatter.format(dob);
            int dob_year = Integer.parseInt(dob_mysql_date_string.substring(0,4));
            int dob_month = Integer.parseInt(dob_mysql_date_string.substring(5,7));
            int dob_day = Integer.parseInt(dob_mysql_date_string.substring(8));
//
            SystemAdministrator sa = new SystemAdministrator();
            sa.setUsername(getUsername());
            sa.setPassword(getPassword());
            sa.editDepartmentOfficer(String.valueOf(cmb_department_officer__id.getSelectedItem()),
                    txt_first_name.getText(),
                    txt_last_name.getText(),
                    getDo_username(),
                    txt_address.getText(),
                    LocalDate.of(dob_year, dob_month, dob_day),
                    txt_email.getText(),
                    txt_nic.getText(),
                    getDo_password()
                    );

            JOptionPane.showMessageDialog(this, "Department Officer Successfully Added!");
            SystemAdministratorDashboard sad = new SystemAdministratorDashboard(getUsername(), getPassword());
            sad.setVisible(true);
            dispose();
            

        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void cmb_department_officer__idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_department_officer__idItemStateChanged
        // TODO add your handling code here:
        if (String.valueOf(cmb_department_officer__id.getSelectedItem()).equals("Select")) {
            txt_first_name.setText("");
            txt_last_name.setText("");
            txt_address.setText("");
            dtch_dob.setDate(null);
            txt_email.setText("");
            txt_nic.setText("");        
        } else {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver"); 
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
                String sql = "SELECT first_name, last_name, username, address, dob, email, nic, password FROM user WHERE role = 'Department Officer' AND id = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, String.valueOf(cmb_department_officer__id.getSelectedItem()));
                ResultSet rs = pst.executeQuery();

                while (rs.next()) {
                    txt_first_name.setText(rs.getString("first_name"));
                    txt_last_name.setText(rs.getString("last_name"));
                    txt_address.setText(rs.getString("address"));
                    txt_email.setText(rs.getString("email"));
//                    Obtaining the date of birth from the db in the correct format
                    String dateValue = rs.getString("dob"); // What ever column
                    java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
//                    --------------
                    dtch_dob.setDate(date);
                    txt_nic.setText(rs.getString("nic"));
                    
//                    Passing username and password for editing / edit button action
                    setDo_username(rs.getString("username"));
                    setDo_password(rs.getString("password"));
                
                    
                    
                } 

                conn.close();
            } catch (Exception e) {
                lbl_error_message.setText("Failiure: " + e);
                System.out.println("Failiure: " + e);
            }

        }
    }//GEN-LAST:event_cmb_department_officer__idItemStateChanged

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        if (String.valueOf(cmb_department_officer__id.getSelectedItem()).equals("Select")) {
            lbl_error_message.setText("You must select a department officer id in order to delete!");
        } else {
            SystemAdministrator sa = new SystemAdministrator();
            String message = (sa.deleteDepartmentOfficer(String.valueOf(cmb_department_officer__id.getSelectedItem())));
            if (message.equals("You cannot delete an officer withou asigning another officer for wildlife protected areas he is incharge of.")) {
                lbl_error_message.setText(message + " and assigning anothe upservisors who works under him.");
            } else  {
                JOptionPane.showMessageDialog(this, "Deletion Successful!");
                SystemAdministratorDashboard sad = new SystemAdministratorDashboard(getUsername(), getPassword());
                sad.setVisible(true);
                dispose();
                
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AlterDepartmentOfficerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AlterDepartmentOfficerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AlterDepartmentOfficerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AlterDepartmentOfficerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AlterDepartmentOfficerForm("Admin","Cypher").setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JComboBox<String> cmb_department_officer__id;
    private com.toedter.calendar.JDateChooser dtch_dob;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_department_officer_id;
    private javax.swing.JLabel lbl_dob;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_error_message;
    private javax.swing.JLabel lbl_instructions;
    private javax.swing.JLabel lbl_instructions1;
    private javax.swing.JLabel lbl_instructions2;
    private javax.swing.JLabel lbl_instructions3;
    private javax.swing.JLabel lbl_last_name;
    private javax.swing.JLabel lbl_nic;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_first_name;
    private javax.swing.JTextField txt_last_name;
    private javax.swing.JTextField txt_nic;
    // End of variables declaration//GEN-END:variables
}
