
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mws_a
 */
public class AlterElephantLocationForm extends javax.swing.JFrame {

    /**
     * Creates new form AlterElephantLocationForm
     */
    private String rangerId;
    private String wpa;
    private String username;
    private String password;
            
    public AlterElephantLocationForm(String rangerId, String wpa, String username, String password) {
        initComponents();
        setRangerId(rangerId);
        setWpa(wpa);
        populateIdCmb();
        populateElephantCmb();
    }
    
//    Stters 

    public void setRangerId(String rangerId) {
        this.rangerId = rangerId;
    }

    public void setWpa(String wpa) {
        this.wpa = wpa;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    
    
//    Getters
    
    public String getRangerId() {

        return rangerId;
    }

    public String getWpa() {
        return wpa;
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmb_id = new javax.swing.JComboBox<>();
        lbl_id = new javax.swing.JLabel();
        lbl_latitude = new javax.swing.JLabel();
        txt_latitude = new javax.swing.JTextField();
        txt_longitude = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        lbl_longitude = new javax.swing.JLabel();
        lbl_error_message = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        cmb_elephant = new javax.swing.JComboBox<>();
        lbl_elephant = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_instructions5 = new javax.swing.JLabel();
        lbl_instructions6 = new javax.swing.JLabel();
        lbl_instructions7 = new javax.swing.JLabel();
        lbl_instructions8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(250, 350));

        jPanel1.setBackground(new java.awt.Color(248, 249, 250));
        jPanel1.setLayout(null);

        cmb_id.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmb_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cmb_id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_idItemStateChanged(evt);
            }
        });
        jPanel1.add(cmb_id);
        cmb_id.setBounds(110, 170, 180, 40);

        lbl_id.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_id.setText("ID");
        jPanel1.add(lbl_id);
        lbl_id.setBounds(30, 170, 100, 40);

        lbl_latitude.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_latitude.setText("Latitude");
        jPanel1.add(lbl_latitude);
        lbl_latitude.setBounds(30, 290, 80, 40);

        txt_latitude.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_latitude);
        txt_latitude.setBounds(110, 290, 180, 40);

        txt_longitude.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_longitude);
        txt_longitude.setBounds(110, 350, 180, 40);

        btn_edit.setBackground(new java.awt.Color(33, 37, 41));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(248, 249, 250));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit);
        btn_edit.setBounds(210, 430, 80, 50);

        lbl_longitude.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_longitude.setText("Longitude");
        jPanel1.add(lbl_longitude);
        lbl_longitude.setBounds(30, 350, 90, 40);

        lbl_error_message.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_error_message.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_error_message);
        lbl_error_message.setBounds(40, 540, 810, 50);

        btn_back.setBackground(new java.awt.Color(33, 37, 41));
        btn_back.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_back.setForeground(new java.awt.Color(248, 249, 250));
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(30, 430, 80, 50);

        btn_delete.setBackground(new java.awt.Color(33, 37, 41));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(248, 249, 250));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);
        btn_delete.setBounds(120, 430, 80, 50);

        cmb_elephant.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmb_elephant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jPanel1.add(cmb_elephant);
        cmb_elephant.setBounds(110, 230, 180, 40);

        lbl_elephant.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_elephant.setText("Elephant");
        jPanel1.add(lbl_elephant);
        lbl_elephant.setBounds(30, 230, 100, 40);

        lbl_title.setBackground(new java.awt.Color(33, 37, 41));
        lbl_title.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        lbl_title.setText("Alter Elephant Location");
        lbl_title.setOpaque(true);
        jPanel1.add(lbl_title);
        lbl_title.setBounds(-10, 0, 920, 100);

        jPanel2.setBackground(new java.awt.Color(248, 249, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instructions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(33, 37, 41))); // NOI18N

        lbl_instructions5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instructions5.setText("All fields must be filled with valid data to edit information");
        lbl_instructions5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_instructions6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instructions6.setText("Lattitude and longitude must be numbers to edit information");
        lbl_instructions6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_instructions7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instructions7.setText("A valid elephant should be picked out in order to edit");
        lbl_instructions7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_instructions8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instructions8.setText("Elephant location id should be picked and it cannot be Select to edit and delete ");
        lbl_instructions8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_instructions5, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_instructions6, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_instructions7, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(437, 437, 437))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_instructions8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_instructions5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_instructions6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_instructions7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lbl_instructions8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(320, 170, 530, 220);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        lbl_error_message.setText("");
        if (txt_latitude.getText().equals("") || 
                !Validator.isNumber(txt_latitude.getText()) ||
                txt_longitude.getText().equals("") || 
                !Validator.isNumber(txt_longitude.getText()) ||
                String.valueOf(cmb_id.getSelectedItem()).equals("Select") ||
                String. valueOf(cmb_elephant).equals("")) {
            lbl_error_message.setText("Read the instructions agin and enter valid information!");
        } else {
            ElephantLocation el = new ElephantLocation();
            el.setGeographic_coordinates(txt_latitude.getText() + ", " + txt_longitude.getText());
            el.setElephant(String.valueOf(cmb_elephant.getSelectedItem()));
            el.setId(String.valueOf(cmb_id.getSelectedItem()));
            el.edit(); 
            JOptionPane.showMessageDialog(this,"Elephant location is added successfully.");  
            WildlifeRangerDashboard wrd = new WildlifeRangerDashboard(getRangerId(),getUsername(), getPassword(), "Wildlife Ranger");
            wrd.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        WildlifeRangerDashboard wrd = new WildlifeRangerDashboard(getRangerId(), "xx", "xx", "xx");
        wrd.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void cmb_idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_idItemStateChanged
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT id, geographic_coordinates, elephant FROM elephantlocation WHERE id = ?";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, String.valueOf(String.valueOf(cmb_id.getSelectedItem())));
            ResultSet rs = pst.executeQuery();            
            System.out.println("WPA: " + getWpa());

            if (rs.next()) {
                String location[] = rs.getString("geographic_coordinates").split(",");
                String latitude = location[0].replaceAll("\\s", "");;
                String longitude = location[1].replaceAll("\\s", "");;
                txt_latitude.setText(latitude);
                txt_longitude.setText(longitude);
                cmb_elephant.setSelectedItem(rs.getString("elephant"));
            } 

            conn.close();
        } catch (Exception e) {
            lbl_error_message.setText("Failiure: " + e);
            System.out.println("Failiure: " + e);
        }
    }//GEN-LAST:event_cmb_idItemStateChanged

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        lbl_error_message.setText("");
        if (String.valueOf(cmb_id.getSelectedItem()).equals("Select") ||
                String.valueOf(cmb_elephant.getSelectedItem()).equals("Select") ||
                txt_latitude.getText().equals("") ||
                !Validator.isNumber(txt_latitude.getText()) ||
                txt_longitude.getText().equals("") ||
                !Validator.isNumber(txt_longitude.getText())
                ){
            lbl_error_message.setText("Refer to the instructions and insert valid vlues ");
        } else {
            ElephantLocation el = new ElephantLocation();
            el.setId(String.valueOf(cmb_id.getSelectedItem()));
            el.delete(); 
            JOptionPane.showMessageDialog(this,"Elephant location is added successfully.");  
            WildlifeRangerDashboard wrd = new WildlifeRangerDashboard(getRangerId(),getUsername(), getPassword(), "Wildlife Ranger");
            wrd.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void populateIdCmb() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT id FROM elephantlocation";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            System.out.println("WPA: " + getWpa());

            while (rs.next()) {
                cmb_id.addItem(rs.getString("id"));
                System.out.println(rs.getString("id"));
            } 

            conn.close();
        } catch (Exception e) {
            lbl_error_message.setText("Failiure: " + e);
            System.out.println("Failiure: " + e);
        }
    }
    
    private void populateElephantCmb() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT id FROM elephant";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            System.out.println("WPA: " + getWpa());

            while (rs.next()) {
                cmb_elephant.addItem(rs.getString("id"));
                System.out.println(rs.getString("id"));
            } 

            conn.close();
        } catch (Exception e) {
            lbl_error_message.setText("Failiure: " + e);
            System.out.println("Failiure: " + e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AlterElephantLocationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AlterElephantLocationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AlterElephantLocationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AlterElephantLocationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AlterElephantLocationForm("87","11").setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JComboBox<String> cmb_elephant;
    private javax.swing.JComboBox<String> cmb_id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_elephant;
    private javax.swing.JLabel lbl_error_message;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_instructions5;
    private javax.swing.JLabel lbl_instructions6;
    private javax.swing.JLabel lbl_instructions7;
    private javax.swing.JLabel lbl_instructions8;
    private javax.swing.JLabel lbl_latitude;
    private javax.swing.JLabel lbl_longitude;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_latitude;
    private javax.swing.JTextField txt_longitude;
    // End of variables declaration//GEN-END:variables
}
