
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mws_a
 */
public class AlterElephantPopulation extends javax.swing.JFrame {

    /**
     * Creates new form AlterElephantPopulation
     */
    private String rangerId;
    private String wpa;
    private String username;
    private String password;
    
    public AlterElephantPopulation(String rangerId, String wpa, String username, String password) {
        initComponents();
        setRangerId(rangerId);
        setWpa(wpa);
        setUsername(username);
        setPassword(password);
        populateCmbId();
        
    }
    
//    Setters

    public void setRangerId(String rangerId) {

        this.rangerId = rangerId;
    }

    public void setWpa(String wpa) {
        this.wpa = wpa;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    

//    Getters

    public String getRangerId() {

        return rangerId;
    }

    public String getWpa() {
        return wpa;
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }
   
    
//    Other methods
    private void populateCmbId () {;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT id FROM elephantpopulation WHERE wpa = ?";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, getWpa());
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                cmb_id.addItem(rs.getString("id"));
            } 
            conn.close();
        } catch (Exception e) {
            System.out.println("Failiure: " + e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_population = new javax.swing.JLabel();
        txt_population = new javax.swing.JTextField();
        btn_edid = new javax.swing.JButton();
        lbl_error_message = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        cmb_id = new javax.swing.JComboBox<>();
        btn_delete = new javax.swing.JButton();
        lbl_title = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(250, 350));

        jPanel1.setLayout(null);

        lbl_population.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_population.setText("Population");
        jPanel1.add(lbl_population);
        lbl_population.setBounds(20, 190, 90, 40);

        txt_population.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_population);
        txt_population.setBounds(110, 190, 140, 40);

        btn_edid.setBackground(new java.awt.Color(33, 37, 41));
        btn_edid.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_edid.setForeground(new java.awt.Color(248, 249, 250));
        btn_edid.setText("Edit");
        btn_edid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edidActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edid);
        btn_edid.setBounds(150, 250, 100, 50);

        lbl_error_message.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_error_message);
        lbl_error_message.setBounds(20, 420, 230, 40);

        lbl_id.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_id.setText("ID");
        jPanel1.add(lbl_id);
        lbl_id.setBounds(20, 130, 90, 40);

        cmb_id.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmb_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cmb_id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_idItemStateChanged(evt);
            }
        });
        cmb_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_idActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_id);
        cmb_id.setBounds(110, 130, 140, 40);

        btn_delete.setBackground(new java.awt.Color(33, 37, 41));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(248, 249, 250));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);
        btn_delete.setBounds(20, 250, 100, 50);

        lbl_title.setBackground(new java.awt.Color(33, 27, 41));
        lbl_title.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        lbl_title.setText("Alter Population");
        lbl_title.setOpaque(true);
        jPanel1.add(lbl_title);
        lbl_title.setBounds(0, 0, 300, 110);

        btn_close.setBackground(new java.awt.Color(33, 37, 41));
        btn_close.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_close.setForeground(new java.awt.Color(248, 249, 250));
        btn_close.setText("Back");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_close);
        btn_close.setBounds(20, 340, 230, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_edidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edidActionPerformed
        // TODO add your handling code here:
        if (txt_population.getText().equals("") || 
                !Validator.isNumber(txt_population.getText()) || 
                String.valueOf(cmb_id.getSelectedItem()).equals("Select")) {
            lbl_error_message.setText("The population field must be filled and it should be a number");
        } else {
            ElephantPopulation ep = new ElephantPopulation();
            ep.setId(String.valueOf(cmb_id.getSelectedItem()));
            ep.setPopulation(Integer.parseInt(txt_population.getText()));
            ep.edit();
            JOptionPane.showMessageDialog(this,"Elephant location is altered successfully.");  
            WildlifeRangerDashboard wrd = new WildlifeRangerDashboard(getRangerId(),getUsername(), getPassword(), "Wildlife Ranger");
            wrd.setVisible(true);
            setVisible(false);
        }

    }//GEN-LAST:event_btn_edidActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        if (String.valueOf(cmb_id.getSelectedItem()).equals("Select")) {
            lbl_error_message.setText("A vlid population id must be picked from the dropdown");
        } else {
            ElephantPopulation ep = new ElephantPopulation();
            ep.setId(String.valueOf(cmb_id.getSelectedItem()));
            ep.delete();
            JOptionPane.showMessageDialog(this,"Elephant location is deleted successfully.");  
            WildlifeRangerDashboard wrd = new WildlifeRangerDashboard(getRangerId(),getUsername(), getPassword(), "Wildlife Ranger");
            wrd.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void cmb_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_idActionPerformed

    private void cmb_idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_idItemStateChanged
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT id, population FROM elephantpopulation WHERE id = ?";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, String.valueOf(cmb_id.getSelectedItem()));
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                txt_population.setText(rs.getString("population"));
                
            } 
            
            conn.close();
        } catch (Exception e) {
            System.out.println("Failiure: " + e);
        }
    }//GEN-LAST:event_cmb_idItemStateChanged

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        dispose();
        WildlifeRangerDashboard wrd = new WildlifeRangerDashboard(getRangerId(),getUsername(), getPassword(), "Wildlife Ranger");
        wrd.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_closeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AlterElephantPopulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AlterElephantPopulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AlterElephantPopulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AlterElephantPopulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AlterElephantPopulation("87","11").setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edid;
    private javax.swing.JComboBox<String> cmb_id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_error_message;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_population;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_population;
    // End of variables declaration//GEN-END:variables
}
