
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mws_a
 */
public class DepartmentOfficerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form DepartmentOfficerDashboard
     */
//    User properties for login
    private String id;
    private String username;
    private String password;
    private DepartmentOfficer do1;
    private String role;
    private JPanel jpa = new JPanel();
    
    
      
    public DepartmentOfficerDashboard(String id, String username, String password, String role) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setId(id);
        this.setUsername(username);
        this.setPassword(password);
        this.setRole(role);
        updateRangerTable();
        do1 = initiateDepartmentOfficer(id); 
        populateWpaTable();
        populatePersonalInfoPanel();
        displayTotalElephantPopulation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_main = new javax.swing.JPanel();
        btn_personal_info_change = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbl_title = new javax.swing.JLabel();
        lbl_welcome_message = new javax.swing.JLabel();
        pnl_personal_info = new javax.swing.JPanel();
        lbl_first_name = new javax.swing.JLabel();
        lbl_last_name = new javax.swing.JLabel();
        lbl_user_name = new javax.swing.JLabel();
        lbl_nic = new javax.swing.JLabel();
        lbl_dob = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_personal_info_title = new javax.swing.JLabel();
        pnl_wildlife_ranger_section = new javax.swing.JPanel();
        scr_pn_ranger = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_ranger = new javax.swing.JTable();
        btn_add = new javax.swing.JButton();
        btn_alter_ranger = new javax.swing.JButton();
        ptn_wpa_section = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_wpa = new javax.swing.JTable();
        pnl_total_elephant_population = new javax.swing.JPanel();
        lbl_total_elephant_population_title = new javax.swing.JLabel();
        lbl_total_elephant_population = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));

        pnl_main.setBackground(new java.awt.Color(248, 249, 250));
        pnl_main.setMinimumSize(new java.awt.Dimension(600, 600));
        pnl_main.setLayout(null);

        btn_personal_info_change.setBackground(new java.awt.Color(248, 249, 250));
        btn_personal_info_change.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_personal_info_change.setForeground(new java.awt.Color(33, 37, 41));
        btn_personal_info_change.setText("Settings");
        btn_personal_info_change.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btn_personal_info_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personal_info_changeActionPerformed(evt);
            }
        });
        pnl_main.add(btn_personal_info_change);
        btn_personal_info_change.setBounds(1180, 30, 160, 50);

        jButton1.setBackground(new java.awt.Color(248, 249, 250));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(33, 37, 41));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnl_main.add(jButton1);
        jButton1.setBounds(1350, 30, 160, 50);

        lbl_title.setBackground(new java.awt.Color(33, 37, 41));
        lbl_title.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        lbl_title.setText("Department Officer Dashboard");
        lbl_title.setOpaque(true);
        pnl_main.add(lbl_title);
        lbl_title.setBounds(0, 0, 1560, 110);

        lbl_welcome_message.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_welcome_message.setForeground(new java.awt.Color(33, 37, 42));
        lbl_welcome_message.setText("Welcome Message");
        pnl_main.add(lbl_welcome_message);
        lbl_welcome_message.setBounds(20, 120, 220, 40);

        pnl_personal_info.setBackground(new java.awt.Color(33, 37, 41));

        lbl_first_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_first_name.setForeground(new java.awt.Color(248, 249, 250));
        lbl_first_name.setText("FIrst Nam");

        lbl_last_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_last_name.setForeground(new java.awt.Color(248, 249, 250));
        lbl_last_name.setText("Last Name");

        lbl_user_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_user_name.setForeground(new java.awt.Color(248, 249, 250));
        lbl_user_name.setText("Username");

        lbl_nic.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_nic.setForeground(new java.awt.Color(248, 249, 250));
        lbl_nic.setText("NIC");

        lbl_dob.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_dob.setForeground(new java.awt.Color(248, 249, 250));
        lbl_dob.setText("Date of Birth");

        lbl_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(248, 249, 250));
        lbl_email.setText("Email");

        lbl_personal_info_title.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_personal_info_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_personal_info_title.setText("Your Information");

        javax.swing.GroupLayout pnl_personal_infoLayout = new javax.swing.GroupLayout(pnl_personal_info);
        pnl_personal_info.setLayout(pnl_personal_infoLayout);
        pnl_personal_infoLayout.setHorizontalGroup(
            pnl_personal_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_personal_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_personal_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_personal_info_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_first_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_last_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_user_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_dob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_personal_infoLayout.createSequentialGroup()
                        .addComponent(lbl_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_personal_infoLayout.setVerticalGroup(
            pnl_personal_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_personal_infoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_personal_info_title, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_main.add(pnl_personal_info);
        pnl_personal_info.setBounds(20, 170, 290, 420);

        pnl_wildlife_ranger_section.setBackground(new java.awt.Color(248, 249, 250));
        pnl_wildlife_ranger_section.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Wildlife Ranger Operations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(33, 37, 41))); // NOI18N

        tbl_ranger.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tbl_ranger.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Address", "Email", "NIC", "WPA", "DOB", "Registered Date"
            }
        ));
        tbl_ranger.setRowHeight(18);
        tbl_ranger.setRowMargin(2);
        tbl_ranger.setSelectionBackground(new java.awt.Color(33, 37, 41));
        tbl_ranger.setSelectionForeground(new java.awt.Color(248, 249, 250));
        jScrollPane2.setViewportView(tbl_ranger);

        scr_pn_ranger.setViewportView(jScrollPane2);

        btn_add.setBackground(new java.awt.Color(33, 37, 41));
        btn_add.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_add.setForeground(new java.awt.Color(248, 249, 250));
        btn_add.setText("Add Ranger");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_alter_ranger.setBackground(new java.awt.Color(33, 37, 41));
        btn_alter_ranger.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_alter_ranger.setForeground(new java.awt.Color(248, 249, 250));
        btn_alter_ranger.setText("Alter Ranger");
        btn_alter_ranger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alter_rangerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_wildlife_ranger_sectionLayout = new javax.swing.GroupLayout(pnl_wildlife_ranger_section);
        pnl_wildlife_ranger_section.setLayout(pnl_wildlife_ranger_sectionLayout);
        pnl_wildlife_ranger_sectionLayout.setHorizontalGroup(
            pnl_wildlife_ranger_sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_wildlife_ranger_sectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_wildlife_ranger_sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_wildlife_ranger_sectionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_alter_ranger, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scr_pn_ranger, javax.swing.GroupLayout.DEFAULT_SIZE, 1154, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_wildlife_ranger_sectionLayout.setVerticalGroup(
            pnl_wildlife_ranger_sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_wildlife_ranger_sectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_wildlife_ranger_sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_alter_ranger, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(scr_pn_ranger, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_main.add(pnl_wildlife_ranger_section);
        pnl_wildlife_ranger_section.setBounds(330, 430, 1190, 330);

        ptn_wpa_section.setBackground(new java.awt.Color(248, 249, 250));
        ptn_wpa_section.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Wildlife Protected Areas Under Your Supervison", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(33, 37, 41))); // NOI18N

        tbl_wpa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tbl_wpa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Area", "Province", "Date of Declaration", "Elephant Population"
            }
        ));
        tbl_wpa.setRowHeight(18);
        tbl_wpa.setRowMargin(2);
        tbl_wpa.setSelectionBackground(new java.awt.Color(33, 37, 41));
        tbl_wpa.setSelectionForeground(new java.awt.Color(248, 249, 250));
        jScrollPane1.setViewportView(tbl_wpa);

        javax.swing.GroupLayout ptn_wpa_sectionLayout = new javax.swing.GroupLayout(ptn_wpa_section);
        ptn_wpa_section.setLayout(ptn_wpa_sectionLayout);
        ptn_wpa_sectionLayout.setHorizontalGroup(
            ptn_wpa_sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ptn_wpa_sectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1154, Short.MAX_VALUE)
                .addContainerGap())
        );
        ptn_wpa_sectionLayout.setVerticalGroup(
            ptn_wpa_sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptn_wpa_sectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_main.add(ptn_wpa_section);
        ptn_wpa_section.setBounds(330, 170, 1190, 250);

        pnl_total_elephant_population.setBackground(new java.awt.Color(33, 37, 41));

        lbl_total_elephant_population_title.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_total_elephant_population_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_total_elephant_population_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_total_elephant_population_title.setText("Total Elephant Population");

        lbl_total_elephant_population.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_total_elephant_population.setForeground(new java.awt.Color(248, 249, 250));
        lbl_total_elephant_population.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_total_elephant_population.setText("00");

        javax.swing.GroupLayout pnl_total_elephant_populationLayout = new javax.swing.GroupLayout(pnl_total_elephant_population);
        pnl_total_elephant_population.setLayout(pnl_total_elephant_populationLayout);
        pnl_total_elephant_populationLayout.setHorizontalGroup(
            pnl_total_elephant_populationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_total_elephant_populationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_total_elephant_populationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_total_elephant_populationLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_total_elephant_population, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(pnl_total_elephant_populationLayout.createSequentialGroup()
                        .addComponent(lbl_total_elephant_population_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnl_total_elephant_populationLayout.setVerticalGroup(
            pnl_total_elephant_populationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_total_elephant_populationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_total_elephant_population_title, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lbl_total_elephant_population, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_main.add(pnl_total_elephant_population);
        pnl_total_elephant_population.setBounds(20, 600, 290, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_main, javax.swing.GroupLayout.PREFERRED_SIZE, 1559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_main, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        WildLifeRangerAddForm wra = new WildLifeRangerAddForm(getId(), tbl_ranger);
        wra.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_alter_rangerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alter_rangerActionPerformed
        // TODO add your handling code here:
        WildlifeRangerEditDeleteForm wred = new WildlifeRangerEditDeleteForm(getId());
        wred.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_alter_rangerActionPerformed

    private void btn_personal_info_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_personal_info_changeActionPerformed
        // TODO add your handling code here:
        
        System.out.println("Password: " + getPassword());
        PersonalInformationChangeForm picf = new PersonalInformationChangeForm(getId(),getRole());
        picf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_personal_info_changeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoginPanel lp = new LoginPanel();
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    //    Setters
    public void setId(String id) {
        this.id = id;
    }

    
    public void setUsername(String username) {
        this.username = username;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public void setRole(String role) {
        this.role = role;
    }
    
    
  
    
//    getters

    public String getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }
    
    public String getRole() {
        return role;
    }
    
//    Other internal methods
    private void updateRangerTable() {
         try {
                Class.forName("com.mysql.cj.jdbc.Driver"); 
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
                String sql = "SELECT user, wpa FROM wildliferanger WHERE department_officer = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, String.valueOf(getId()));
                ResultSet rs = pst.executeQuery();

                while (rs.next()) {
//                    try {
//                        Class.forName("com.mysql.cj.jdbc.Driver"); 
//                        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
//                        String sql_user = "SELECT id, first_name, last_name, address, wpa FROM wildliferanger WHERE department_officer = ?";
//                        
//                    
//                    } catch (Exception e){
//                        System.out.println("Failiure: " + e);
//                    }
                    String sql_user = "SELECT id, first_name, last_name, username, address, dob, email, nic, registered_date FROM user WHERE id = ?" ;
                    PreparedStatement pst_user = conn.prepareStatement(sql_user);
                    pst_user.setString(1, String.valueOf(rs.getString("user")));
                    ResultSet rs_user = pst_user.executeQuery();
                    
                    if (rs_user.next()) {
                        String id = rs_user.getString("id");
                        String fn = rs_user.getString("first_name");
                        String ln = rs_user.getString("last_name");
                        String ad = rs_user.getString("address");
                        String d = rs_user.getString("dob");
                        String e = rs_user.getString("email");
                        String n = rs_user.getString("nic");
                        String rd = rs_user.getString("registered_date");
                        String w = rs.getString("wpa");
                        
                        String ranger_info[] = {id,fn,ln,ad, e, n, w, d, rd};
                        DefaultTableModel ranger_table = (DefaultTableModel)tbl_ranger.getModel();
                        ranger_table.addRow(ranger_info);
                        
                    } else {
                        System.out.println("Wrong id");
                    }               
                    
                    
                     
                    
                } 
                conn.close();
            } catch (Exception e) {
                System.out.println("Failiure: " + e);
            }
    }
    
    public DepartmentOfficer initiateDepartmentOfficer(String id) {
        DepartmentOfficer do1 = new DepartmentOfficer();
        do1.setId(id);
        return do1;
    }
    
    private void populateWpaTable() {
         try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT id, name, area, province, date_of_declaration FROM wildlifeprotectedarea WHERE department_officer = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, String.valueOf(getId()));
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String sql_max_id = "SELECT MAX(id) FROM elephantpopulation WHERE wpa = ?" ;
                PreparedStatement pst_max_id = conn.prepareStatement(sql_max_id);
                pst_max_id.setString(1, String.valueOf(rs.getString("id")));
                ResultSet rs_max_id = pst_max_id.executeQuery();

                if (rs_max_id.next()) {
                    String id = rs.getString("id");
                    String name = rs.getString("name");
                    String area = rs.getString("area");
                    String province = rs.getString("province");
                    String dod = rs.getString("date_of_declaration");
                    String population = "0";
                    System.out.println(rs_max_id.getString("MAX(id)"));
                    
//                    Getting the latest population from elephant population table
                    String sql_latest_population = "SELECT population FROM elephantpopulation WHERE id = ?" ;
                    PreparedStatement pst_latest_population = conn.prepareStatement(sql_latest_population);
                    pst_latest_population.setString(1, String.valueOf(rs_max_id.getString("MAX(id)")));
                    ResultSet rs_latest_population = pst_latest_population.executeQuery();
                    
                    if (rs_latest_population.next()) {
                        population = rs_latest_population.getString("population");
                        String wpa_info[] = {id, name, area, province, dod, population};
                        DefaultTableModel wpa_table = (DefaultTableModel)tbl_wpa.getModel();
                        wpa_table.addRow(wpa_info);

                    }
                    
                    


                } else {
                    System.out.println("Wrong id");
                }               




            } 
            conn.close();
        } catch (Exception e) {
            System.out.println("Failiure: " + e);
        }
        
    }

    private void populatePersonalInfoPanel() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT first_name, last_name, username, dob, nic, email FROM user WHERE id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, String.valueOf(getId()));
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                lbl_first_name.setText("First Name:" + rs.getString("first_name"));
                lbl_last_name.setText("Last Name:" + rs.getString("last_name"));
                lbl_user_name.setText("Username:" + rs.getString("username"));
                lbl_nic.setText("NIC:" + rs.getString("nic"));
                lbl_dob.setText("Date of Birth:" + rs.getString("dob"));
                lbl_email.setText("Email:" + rs.getString("email"));
                
                lbl_welcome_message.setText("Welcome, " + rs.getString("first_name") + " "+ rs.getString("last_name"));
            } 
            conn.close();
        } catch (Exception e) {
            System.out.println("Failiure: " + e);
        }
    }
    
    private void displayTotalElephantPopulation() {
        CurretElephantPopulation cep = CurretElephantPopulation.instentiateCurrentElephantPopulation();
        lbl_total_elephant_population.setText(String.valueOf(CurretElephantPopulation.getTotalElephantPopulation()));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_alter_ranger;
    private javax.swing.JButton btn_personal_info_change;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_dob;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_first_name;
    private javax.swing.JLabel lbl_last_name;
    private javax.swing.JLabel lbl_nic;
    private javax.swing.JLabel lbl_personal_info_title;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_total_elephant_population;
    private javax.swing.JLabel lbl_total_elephant_population_title;
    private javax.swing.JLabel lbl_user_name;
    private javax.swing.JLabel lbl_welcome_message;
    private javax.swing.JPanel pnl_main;
    private javax.swing.JPanel pnl_personal_info;
    private javax.swing.JPanel pnl_total_elephant_population;
    private javax.swing.JPanel pnl_wildlife_ranger_section;
    private javax.swing.JPanel ptn_wpa_section;
    private javax.swing.JScrollPane scr_pn_ranger;
    private javax.swing.JTable tbl_ranger;
    private javax.swing.JTable tbl_wpa;
    // End of variables declaration//GEN-END:variables

    private void updateRangerTable(char c) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
