
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mws_a
 */
public class DirectorGeneralDashBoard extends javax.swing.JFrame {
    
    private String id;
    private String username;
    private String password;
    private String role;
    private DirectorGeneral dg;
    
    public DirectorGeneralDashBoard(String id, String username, String password, String role) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setId(id);
        this.setUsername(username);
        this.setPassword(password);
        this.setRole(role);
//        lbl_test_id.setText(this.getId());
//        lbl_test_username.setText(this.getUsername());
//        lbl_test_role.setText(this.getRole());
        dg = initiateDirectorGeneral();
//        System.out.println("ID: " + dg.getId());
        populateUserInformatinPanel();
        populateWpaTable();
        setDg(initiateDirectorGeneral());
        lbl_welcome_message.setText("Welcome, " + dg.getFirst_name() + " " + dg.getLast_name());
        
        System.out.println("DGID: " + getDg().getEmail());
        displayTotalElephantPopulation();
//        jPanel1.add(jScrollBar1);
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbl_title = new javax.swing.JLabel();
        pnl_personal_info = new javax.swing.JPanel();
        lbl_first_name = new javax.swing.JLabel();
        lbl_last_name = new javax.swing.JLabel();
        lbl_user_name = new javax.swing.JLabel();
        lbl_nic = new javax.swing.JLabel();
        lbl_dob = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_personal_info_title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        scr_pnl_wpa = new javax.swing.JScrollPane();
        tbl_wpa = new javax.swing.JTable();
        btn_add_wpa = new javax.swing.JButton();
        btn_alter_wpa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_migration_report = new javax.swing.JButton();
        btn_population_report = new javax.swing.JButton();
        lbl_welcome_message = new javax.swing.JLabel();
        pnl_total_elephant_population = new javax.swing.JPanel();
        lbl_total_elephant_population_title = new javax.swing.JLabel();
        lbl_total_elephant_population = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 837));

        jPanel1.setBackground(new java.awt.Color(248, 249, 250));
        jPanel1.setLayout(null);

        btn_logout.setBackground(new java.awt.Color(248, 249, 250));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(33, 37, 41));
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout);
        btn_logout.setBounds(1340, 40, 170, 50);

        jButton1.setBackground(new java.awt.Color(248, 249, 250));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(33, 37, 41));
        jButton1.setText("Settings");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1180, 40, 150, 50);

        lbl_title.setBackground(new java.awt.Color(33, 37, 41));
        lbl_title.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        lbl_title.setText("Director General Dashboard");
        lbl_title.setMaximumSize(new java.awt.Dimension(500, 100));
        lbl_title.setMinimumSize(new java.awt.Dimension(500, 100));
        lbl_title.setOpaque(true);
        lbl_title.setPreferredSize(new java.awt.Dimension(500, 100));
        jPanel1.add(lbl_title);
        lbl_title.setBounds(0, 0, 1550, 120);

        pnl_personal_info.setBackground(new java.awt.Color(33, 37, 41));

        lbl_first_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_first_name.setForeground(new java.awt.Color(248, 249, 250));
        lbl_first_name.setText("FIrst Nam");

        lbl_last_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_last_name.setForeground(new java.awt.Color(248, 249, 250));
        lbl_last_name.setText("Last Name");

        lbl_user_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_user_name.setForeground(new java.awt.Color(248, 249, 250));
        lbl_user_name.setText("Username");

        lbl_nic.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_nic.setForeground(new java.awt.Color(248, 249, 250));
        lbl_nic.setText("NIC");

        lbl_dob.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_dob.setForeground(new java.awt.Color(248, 249, 250));
        lbl_dob.setText("Date of Birth");

        lbl_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(248, 249, 250));
        lbl_email.setText("Email");

        lbl_personal_info_title.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_personal_info_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_personal_info_title.setText("Your Information");

        javax.swing.GroupLayout pnl_personal_infoLayout = new javax.swing.GroupLayout(pnl_personal_info);
        pnl_personal_info.setLayout(pnl_personal_infoLayout);
        pnl_personal_infoLayout.setHorizontalGroup(
            pnl_personal_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_personal_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_personal_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_personal_info_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_first_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_last_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_user_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_dob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_personal_infoLayout.createSequentialGroup()
                        .addComponent(lbl_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_personal_infoLayout.setVerticalGroup(
            pnl_personal_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_personal_infoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_personal_info_title, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(pnl_personal_info);
        pnl_personal_info.setBounds(20, 220, 290, 420);

        jPanel2.setBackground(new java.awt.Color(248, 249, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Wildlife Protected Area Operation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(33, 37, 41))); // NOI18N

        tbl_wpa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tbl_wpa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Area", "Province", "Department Officer", "Elephant Population", "Date of Declaration"
            }
        ));
        tbl_wpa.setRowHeight(18);
        tbl_wpa.setRowMargin(2);
        tbl_wpa.setSelectionBackground(new java.awt.Color(33, 37, 41));
        tbl_wpa.setSelectionForeground(new java.awt.Color(248, 249, 250));
        scr_pnl_wpa.setViewportView(tbl_wpa);

        btn_add_wpa.setBackground(new java.awt.Color(33, 37, 41));
        btn_add_wpa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_add_wpa.setForeground(new java.awt.Color(248, 249, 250));
        btn_add_wpa.setText("Add Wildlife Protected Area");
        btn_add_wpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_wpaActionPerformed(evt);
            }
        });

        btn_alter_wpa.setBackground(new java.awt.Color(33, 37, 41));
        btn_alter_wpa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_alter_wpa.setForeground(new java.awt.Color(248, 249, 250));
        btn_alter_wpa.setText("Alter WPA");
        btn_alter_wpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alter_wpaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 701, Short.MAX_VALUE)
                        .addComponent(btn_alter_wpa, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_add_wpa, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scr_pnl_wpa))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_wpa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_alter_wpa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scr_pnl_wpa, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(330, 220, 1190, 420);

        jPanel3.setBackground(new java.awt.Color(248, 249, 250));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Report Operations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(33, 37, 41))); // NOI18N

        btn_migration_report.setBackground(new java.awt.Color(33, 37, 41));
        btn_migration_report.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_migration_report.setForeground(new java.awt.Color(248, 249, 250));
        btn_migration_report.setText("Elephant Migration Report");
        btn_migration_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_migration_reportActionPerformed(evt);
            }
        });

        btn_population_report.setBackground(new java.awt.Color(33, 37, 41));
        btn_population_report.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_population_report.setForeground(new java.awt.Color(248, 249, 250));
        btn_population_report.setText("Elephant Population Report");
        btn_population_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_population_reportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_migration_report, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_population_report, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_population_report, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_migration_report, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(330, 660, 530, 120);

        lbl_welcome_message.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_welcome_message.setForeground(new java.awt.Color(33, 37, 41));
        lbl_welcome_message.setText("Welcome Message");
        jPanel1.add(lbl_welcome_message);
        lbl_welcome_message.setBounds(30, 150, 550, 40);

        pnl_total_elephant_population.setBackground(new java.awt.Color(33, 37, 41));

        lbl_total_elephant_population_title.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_total_elephant_population_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_total_elephant_population_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_total_elephant_population_title.setText("Total Elephant Population");

        lbl_total_elephant_population.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_total_elephant_population.setForeground(new java.awt.Color(248, 249, 250));
        lbl_total_elephant_population.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_total_elephant_population.setText("00");

        javax.swing.GroupLayout pnl_total_elephant_populationLayout = new javax.swing.GroupLayout(pnl_total_elephant_population);
        pnl_total_elephant_population.setLayout(pnl_total_elephant_populationLayout);
        pnl_total_elephant_populationLayout.setHorizontalGroup(
            pnl_total_elephant_populationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_total_elephant_populationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_total_elephant_populationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_total_elephant_populationLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_total_elephant_population, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(pnl_total_elephant_populationLayout.createSequentialGroup()
                        .addComponent(lbl_total_elephant_population_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnl_total_elephant_populationLayout.setVerticalGroup(
            pnl_total_elephant_populationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_total_elephant_populationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_total_elephant_population_title, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lbl_total_elephant_population, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pnl_total_elephant_population);
        pnl_total_elephant_population.setBounds(20, 650, 290, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_wpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_wpaActionPerformed
        // TODO add your handling code here:
        WpaAddForm waf = new WpaAddForm(getId(), getUsername(), getPassword());
        waf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_add_wpaActionPerformed

    private void btn_alter_wpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alter_wpaActionPerformed
        // TODO add your handling code here:
        WpaAlterForm waf = new WpaAlterForm(getId(), getUsername(), getPassword());
        waf.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_btn_alter_wpaActionPerformed

    private void btn_population_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_population_reportActionPerformed
        // TODO add your handling code here:
        ElephantPopulationReport elp = new ElephantPopulationReport(getId(), getUsername(), getPassword(), "Director General");
        elp.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_population_reportActionPerformed

    private void btn_migration_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_migration_reportActionPerformed
        // TODO add your handling code here:
        ElephantMigrationReport emp = new ElephantMigrationReport(getId(), getUsername(), getPassword(), "Director General");
        emp.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_migration_reportActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        LoginPanel lp = new LoginPanel();
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PersonalInformationChangeForm picf = new PersonalInformationChangeForm(getId(), getRole());
        picf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

//    Setters
    public void setId(String id) {
        this.id = id;
    }

    
    public void setUsername(String username) {
        this.username = username;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public void setDg(DirectorGeneral dg) {
        this.dg = dg;
    }
    
    
    
  
    
//    getters

    public String getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }
    
    public String getRole() {
        return role;
    }

    public DirectorGeneral getDg() {
        return dg;
    }

        
    
//    Other methods
    
    private DirectorGeneral initiateDirectorGeneral () {
        DirectorGeneral dg = new DirectorGeneral();
        dg.setId(getId()); 
//        Getting director general information from the the database to update the instance
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT first_name, last_name, username, dob, email, nic FROM user WHERE id= ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, getId());
            ResultSet rs = pst.executeQuery();

            while (rs.next()) { 
                dg.setFirst_name(rs.getString("first_name"));
                dg.setLast_name(rs.getString("last_name"));
//                Setting up date format
                String dob = rs.getString("dob"); 
                int dob_year = Integer.parseInt(dob.substring(0,4));
                int dob_month = Integer.parseInt(dob.substring(5,7));
                int dob_day = Integer.parseInt(dob.substring(8));
//                --------------------------------------
                dg.setDate_of_birth(LocalDate.of(dob_year, dob_month, dob_day));
                dg.setUsername(rs.getString("username"));
                dg.setNic(rs.getString("nic"));
                dg.setEmail(rs.getString("email"));
            }
            conn.close();
        } catch (Exception e) {
            System.out.println("Failiure: " + e);
        }
        
        return dg;    
    }
    
    private void populateUserInformatinPanel () {
        lbl_first_name.setText("First Name: " + dg.getFirst_name());
        lbl_last_name.setText("Last Name: " + dg.getLast_name());
        lbl_user_name.setText("Username: " + dg.getUsername());
        lbl_dob.setText("Date of Birth: " + String.valueOf(dg.getDate_of_birth()));
        lbl_email.setText("Email: " + dg.getEmail());
        lbl_nic.setText("NIC: " + dg.getNic());
    }
    
    private void populateWpaTable() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT id, name, area, date_of_declaration, province, department_officer FROM wildlifeprotectedarea";

            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String sql_population = "SELECT population FROM elephantpopulation WHERE wpa= ?";
                PreparedStatement pst_population = conn.prepareStatement(sql_population);
                pst_population.setString(1, rs.getString("id"));                
                ResultSet rs_population= pst_population.executeQuery();
                System.out.println("Habitat: " + rs.getString("id"));
                
                
//                Setting up values for wpa table
                String id = rs.getString("id");
                String name = rs.getString("name");
                String area = rs.getString("area");
                String province = rs.getString("province");
                String department_officer = rs.getString("department_officer");
                String population = "0"; // Population for wpa is not obtained yet 
                String date_of_declaration = rs.getString("date_of_declaration");
                if (rs_population.next()) {
                    population = rs_population.getString("population"); // Population for wap will only be obtained if it is added otherwise it would be zero                    
                }
                    String wpa_info[] = {id, name, area, province, department_officer, population, date_of_declaration };
                    
                    DefaultTableModel wpa_table = (DefaultTableModel)tbl_wpa.getModel();
                    wpa_table.addRow(wpa_info);
            } 
            conn.close();
        } catch (Exception e) {
            System.out.println("Failiure: " + e);
        }
    }
    
    private void displayTotalElephantPopulation() {
        CurretElephantPopulation cep = CurretElephantPopulation.instentiateCurrentElephantPopulation();
        lbl_total_elephant_population.setText(String.valueOf(CurretElephantPopulation.getTotalElephantPopulation()));
    }
    
    

    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_wpa;
    private javax.swing.JButton btn_alter_wpa;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_migration_report;
    private javax.swing.JButton btn_population_report;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_dob;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_first_name;
    private javax.swing.JLabel lbl_last_name;
    private javax.swing.JLabel lbl_nic;
    private javax.swing.JLabel lbl_personal_info_title;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_total_elephant_population;
    private javax.swing.JLabel lbl_total_elephant_population_title;
    private javax.swing.JLabel lbl_user_name;
    private javax.swing.JLabel lbl_welcome_message;
    private javax.swing.JPanel pnl_personal_info;
    private javax.swing.JPanel pnl_total_elephant_population;
    private javax.swing.JScrollPane scr_pnl_wpa;
    private javax.swing.JTable tbl_wpa;
    // End of variables declaration//GEN-END:variables
}
