
import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mws_a
 */
public class EditDirectorGeneral extends javax.swing.JFrame {

    /**
     * Creates new form EditDirectorGeneral
     */
    private String username;
    private String password;
    
//    Director general properties
    private String dg_id;
    
    public EditDirectorGeneral(String username, String password) {
        initComponents();
        populateForm();
        setUsername(username);
        setPassword(password);
    }
    
//    Setters

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    

    public void setDg_id(String dg_id) {
        this.dg_id = dg_id;
    }
    
    
//    Getters
    public String getDg_id() {
        return dg_id;
        
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }
    
    

//    Populate form
    private void populateForm() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "Select id, first_name, last_name, username, address, dob, email, nic, password, registered_date  FROM user WHERE role = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, "Director General");
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                setDg_id(rs.getString("id"));
                txt_first_name.setText(rs.getString("first_name"));
                txt_last_name.setText(rs.getString("last_name"));
                txt_address.setText(rs.getString("address"));
                txt_email.setText(rs.getString("email"));
//                Setting up date of birth
                String dateValue = rs.getString("dob"); // What ever column
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
                dtch_dob.setDate(date);
                txt_nic.setText(rs.getString("nic"));
            }
            
            System.out.println("Success!");
            conn.close();
        } catch (Exception e) {
            System.out.println("Failiure!" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_title1 = new javax.swing.JLabel();
        lbl_last_name = new javax.swing.JLabel();
        txt_first_name = new javax.swing.JTextField();
        txt_last_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        lbl_address = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        dtch_dob = new com.toedter.calendar.JDateChooser();
        lbl_dob = new javax.swing.JLabel();
        lbl_nic = new javax.swing.JLabel();
        txt_nic = new javax.swing.JTextField();
        btn_close = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        lbl_error_message = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_instructions = new javax.swing.JLabel();
        lbl_instructions1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 550));

        jPanel1.setLayout(null);

        lbl_title.setBackground(new java.awt.Color(33, 37, 41));
        lbl_title.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        lbl_title.setText("Alter Director General");
        lbl_title.setOpaque(true);
        jPanel1.add(lbl_title);
        lbl_title.setBounds(0, 0, 780, 90);

        lbl_title1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_title1.setText("First Name");
        jPanel1.add(lbl_title1);
        lbl_title1.setBounds(20, 120, 100, 40);

        lbl_last_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_last_name.setText("Last Name");
        jPanel1.add(lbl_last_name);
        lbl_last_name.setBounds(20, 170, 110, 40);

        txt_first_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_first_name);
        txt_first_name.setBounds(120, 120, 230, 40);

        txt_last_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_last_name);
        txt_last_name.setBounds(120, 170, 230, 40);

        txt_address.setColumns(20);
        txt_address.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_address.setRows(5);
        jScrollPane1.setViewportView(txt_address);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 220, 230, 116);

        lbl_address.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_address.setText("Address");
        jPanel1.add(lbl_address);
        lbl_address.setBounds(20, 250, 70, 30);

        lbl_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_email.setText("Email");
        jPanel1.add(lbl_email);
        lbl_email.setBounds(20, 320, 110, 40);

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_email);
        txt_email.setBounds(120, 320, 230, 40);

        dtch_dob.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dtch_dob);
        dtch_dob.setBounds(120, 370, 230, 40);

        lbl_dob.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_dob.setText("Date of Birth");
        jPanel1.add(lbl_dob);
        lbl_dob.setBounds(20, 370, 100, 40);

        lbl_nic.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_nic.setText("NIC");
        jPanel1.add(lbl_nic);
        lbl_nic.setBounds(20, 420, 110, 40);

        txt_nic.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_nic);
        txt_nic.setBounds(120, 420, 230, 40);

        btn_close.setBackground(new java.awt.Color(33, 37, 41));
        btn_close.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_close.setForeground(new java.awt.Color(248, 249, 250));
        btn_close.setText("Back");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_close);
        btn_close.setBounds(20, 510, 110, 50);

        btn_clear.setBackground(new java.awt.Color(33, 37, 41));
        btn_clear.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(248, 249, 250));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear);
        btn_clear.setBounds(140, 510, 110, 50);

        lbl_error_message.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_error_message.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_error_message);
        lbl_error_message.setBounds(20, 570, 750, 50);

        btn_edit.setBackground(new java.awt.Color(33, 37, 41));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(248, 249, 250));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit);
        btn_edit.setBounds(260, 510, 110, 50);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instructions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(33, 37, 41))); // NOI18N

        lbl_instructions.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instructions.setText("Names should be something other than First Lame and Last Lame.");

        lbl_instructions1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instructions1.setText("Make sure that you filled all fields.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_instructions1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_instructions1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(370, 110, 400, 210);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        SystemAdministratorDashboard sad = new SystemAdministratorDashboard(getUsername(), getPassword());
        sad.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_first_name.setText("");
        txt_last_name.setText("");
        txt_address.setText("");
        dtch_dob.setDate(null);
        txt_email.setText("");
        txt_nic.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        if (txt_first_name.getText().equals("First Name") ||
            txt_first_name.getText().equals("") ||
            txt_last_name.getText().equals("Last Name") ||
            txt_last_name.getText().equals("") ||
            txt_address.getText().equals("") ||
            dtch_dob.getDate() == null ||
            txt_email.getText().equals("") ||
            !Validator.validateEmailFormat(txt_email.getText()) ||
            txt_nic.getText().equals("") ) {
            lbl_error_message.setText("Please follow the instructions and enter valid data!");
            
        } else if (Validator.validateRole(getDg_id(), "Director General")) {
            SystemAdministrator sa = new SystemAdministrator();
            sa.setPassword("Admin");
            sa.setPassword("cypher");
//            Setting up date of birth format
            Date dob = dtch_dob.getDate();
            SimpleDateFormat formatter = new SimpleDateFormat("YYYY-MM-d");
            String dob_mysql_date_string = formatter.format(dob);
            int dob_year = Integer.parseInt(dob_mysql_date_string.substring(0,4));
            int dob_month = Integer.parseInt(dob_mysql_date_string.substring(5,7));
            int dob_day = Integer.parseInt(dob_mysql_date_string.substring(8));
//            ----------------
            String message = sa.editDirectorGeneral(getDg_id(), 
                    txt_first_name.getText(), 
                    txt_last_name.getText(), 
                    txt_address.getText(), 
                    txt_email.getText(), 
                    LocalDate.of(dob_year, dob_month, dob_day), 
                    txt_nic.getText());
            JOptionPane.showMessageDialog(this, "The director general information is successfully edited. New credentials:" + message);
            SystemAdministratorDashboard sad = new SystemAdministratorDashboard(getUsername(), getPassword());
            sad.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btn_editActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EditDirectorGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EditDirectorGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EditDirectorGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EditDirectorGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditDirectorGeneral("Admin","cypher").setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_edit;
    private com.toedter.calendar.JDateChooser dtch_dob;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_dob;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_error_message;
    private javax.swing.JLabel lbl_instructions;
    private javax.swing.JLabel lbl_instructions1;
    private javax.swing.JLabel lbl_last_name;
    private javax.swing.JLabel lbl_nic;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_first_name;
    private javax.swing.JTextField txt_last_name;
    private javax.swing.JTextField txt_nic;
    // End of variables declaration//GEN-END:variables
}
