
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mws_a
 */
public class ElephantAlterForm extends javax.swing.JFrame {

    /**
     * Creates new form ElephantAlterForm
     */
    private String rangerId;
    private String wpa;
    private String username;
    private String password;
    
    public ElephantAlterForm(String rangerId, String wpa, String username, String password) {
        initComponents();
        setRangerId(rangerId);
        setWpa(wpa);
        setUsername(username);
        setPassword(password);
        populateIdCmb();
        populateHabitatCmb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        lbl_gender = new javax.swing.JLabel();
        cmb_gender = new javax.swing.JComboBox<>();
        txt_height = new javax.swing.JTextField();
        txt_weight = new javax.swing.JTextField();
        lbl_weight = new javax.swing.JLabel();
        lbl_height = new javax.swing.JLabel();
        lbl_habitat = new javax.swing.JLabel();
        cmb_habitat = new javax.swing.JComboBox<>();
        btn_edit = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();
        cmb_id = new javax.swing.JComboBox<>();
        lbl_error_message = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        cmb_status = new javax.swing.JComboBox<>();
        btn_delete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_instructions5 = new javax.swing.JLabel();
        lbl_instructions6 = new javax.swing.JLabel();
        lbl_instructions7 = new javax.swing.JLabel();
        lbl_instructions8 = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alter Elephant Information");
        setMinimumSize(new java.awt.Dimension(960, 700));
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setBackground(new java.awt.Color(248, 249, 250));
        jPanel1.setLayout(null);

        lbl_title.setBackground(new java.awt.Color(33, 37, 41));
        lbl_title.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        lbl_title.setText("Elephant alter form");
        lbl_title.setOpaque(true);
        jPanel1.add(lbl_title);
        lbl_title.setBounds(0, 0, 990, 100);

        txt_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_name);
        txt_name.setBounds(170, 190, 260, 40);

        lbl_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_name.setText("Name");
        jPanel1.add(lbl_name);
        lbl_name.setBounds(10, 190, 140, 40);

        lbl_gender.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_gender.setText("Gender");
        jPanel1.add(lbl_gender);
        lbl_gender.setBounds(10, 240, 140, 40);

        cmb_gender.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        jPanel1.add(cmb_gender);
        cmb_gender.setBounds(170, 240, 260, 40);

        txt_height.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_height);
        txt_height.setBounds(170, 290, 260, 40);

        txt_weight.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_weightActionPerformed(evt);
            }
        });
        jPanel1.add(txt_weight);
        txt_weight.setBounds(170, 340, 260, 40);

        lbl_weight.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_weight.setText("Weight (in Tons)");
        jPanel1.add(lbl_weight);
        lbl_weight.setBounds(10, 340, 140, 40);

        lbl_height.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_height.setText("Height (in meters)");
        jPanel1.add(lbl_height);
        lbl_height.setBounds(10, 290, 160, 40);

        lbl_habitat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_habitat.setText("Habitat");
        jPanel1.add(lbl_habitat);
        lbl_habitat.setBounds(10, 390, 140, 40);

        cmb_habitat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmb_habitat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jPanel1.add(cmb_habitat);
        cmb_habitat.setBounds(170, 390, 260, 40);

        btn_edit.setBackground(new java.awt.Color(33, 37, 41));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(248, 249, 250));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit);
        btn_edit.setBounds(290, 500, 100, 50);

        lbl_id.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_id.setText("ID");
        jPanel1.add(lbl_id);
        lbl_id.setBounds(10, 140, 140, 40);

        cmb_id.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmb_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cmb_id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_idItemStateChanged(evt);
            }
        });
        jPanel1.add(cmb_id);
        cmb_id.setBounds(170, 140, 260, 40);

        lbl_error_message.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_error_message.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_error_message);
        lbl_error_message.setBounds(20, 620, 880, 30);

        lbl_status.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_status.setText("Status");
        jPanel1.add(lbl_status);
        lbl_status.setBounds(10, 440, 150, 40);

        cmb_status.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Alive", "Dead" }));
        jPanel1.add(cmb_status);
        cmb_status.setBounds(170, 440, 260, 40);

        btn_delete.setBackground(new java.awt.Color(33, 37, 41));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(248, 249, 250));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);
        btn_delete.setBounds(180, 500, 100, 50);

        jPanel2.setBackground(new java.awt.Color(248, 249, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instructions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(33, 37, 41))); // NOI18N

        lbl_instructions5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instructions5.setText("There should not be any empty fields to alter elephant information");
        lbl_instructions5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_instructions6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instructions6.setText("All drop downs should have valid values other than Select to alter information");
        lbl_instructions6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_instructions7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instructions7.setText("A valid Id must be picked for to delete");
        lbl_instructions7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_instructions8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instructions8.setText("Height and weight must be number values");
        lbl_instructions8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_instructions6)
                    .addComponent(lbl_instructions5, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_instructions7, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_instructions8, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_instructions5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_instructions6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_instructions7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_instructions8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(460, 130, 520, 240);

        btn_close.setBackground(new java.awt.Color(33, 37, 41));
        btn_close.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_close.setForeground(new java.awt.Color(248, 249, 250));
        btn_close.setText("Back");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_close);
        btn_close.setBounds(70, 500, 100, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void setRangerId(String rangerId) {    

        this.rangerId = rangerId;
    }

    public void setWpa(String wpa) {
        this.wpa = wpa;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    

//    Getters

    public String getRangerId() {
        return rangerId;
    }

    public String getWpa() {
        return wpa;
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }

    
    
    
    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        lbl_error_message.setText("");
        if (txt_name.getText().equals("") ||
            String.valueOf(cmb_gender.getSelectedItem()).equals("Select") ||
            txt_height.getText().equals("") ||
            !Validator.isNumber(txt_height.getText()) ||
            txt_weight.getText().equals("") ||
            !Validator.isNumber(txt_weight.getText()) ||
            String.valueOf(cmb_habitat.getSelectedItem()).equals("Select") ||
            String.valueOf(cmb_status.getSelectedItem()).equals("Select")
        ) {
            lbl_error_message.setText("Please enter a vlid input");
        } else {
            Elephant e = new Elephant();
            e.setId(String.valueOf(cmb_id.getSelectedItem()));
            e.setPicture("xxx");
            e.setName(txt_name.getText());
            e.setGender(String.valueOf(cmb_gender.getSelectedItem()));
            e.setHeight(txt_height.getText());
            e.setWeight(txt_weight.getText());
            e.setHabitat(String.valueOf(cmb_habitat.getSelectedItem()));
            e.setStatus(String.valueOf(cmb_status.getSelectedItem()));
            e.setRegistered_date(String.valueOf(LocalDate.now()));
            e.edit();
            
            JOptionPane.showMessageDialog(this, "Elephant Successfully Edited!");
            WildlifeRangerDashboard wrd = new WildlifeRangerDashboard(getRangerId(), getUsername(), getPassword(), "Wildlife Ranger");
            wrd.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void cmb_idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_idItemStateChanged
        // TODO add your handling code here:
//        lbl_error_message.setText(String.valueOf(cmb_id.getSelectedItem()));
        String id = String.valueOf(cmb_id.getSelectedItem());
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT id, picture, chip_number, name, gender, height, weight, habitat, status, registered_date FROM elephant WHERE id = ?";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, id);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                txt_name.setText(rs.getString("name"));
                cmb_gender.setSelectedItem(rs.getString("gender"));
                txt_height.setText(rs.getString("height"));
                txt_weight.setText(rs.getString("weight"));
                cmb_habitat.setSelectedItem(rs.getString("habitat"));
                cmb_status.setSelectedItem(rs.getString("status"));
                
            } 
            
            conn.close();
        } catch (Exception e) {
            System.out.println("Failiure: " + e);
        }
        
      
    }//GEN-LAST:event_cmb_idItemStateChanged

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        String id = String.valueOf(cmb_id.getSelectedItem());
        Elephant e = new Elephant();
        e.setId(id);
        e.delete();
        JOptionPane.showMessageDialog(this, "Elephant Succesfully Deleted!");
        WildlifeRangerDashboard dod = new WildlifeRangerDashboard(getRangerId(), getUsername(), getPassword(), "Wildlife Ranger");
        dod.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        
        WildlifeRangerDashboard dod = new WildlifeRangerDashboard(getRangerId(), getUsername(), getPassword(), "Wildlife Ranger");
        dod.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void txt_weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_weightActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ElephantAlterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ElephantAlterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ElephantAlterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ElephantAlterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ElephantAlterForm("87","11").setVisible(true);
//            }
//        });
//    }
    
    private void populateHabitatCmb () {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT id FROM habitat WHERE wpa = ?";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, getWpa());
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                cmb_habitat.addItem(rs.getString("id"));
            } 
            
            conn.close();
        } catch (Exception e) {
            System.out.println("Failiure: " + e);
        }
        
    }
    
    private void populateIdCmb () {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT id FROM habitat WHERE wpa = ?";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, getWpa());
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String sql_elephant = "SELECT id FROM elephant WHERE habitat = ?";

                PreparedStatement pst_elephant = conn.prepareStatement(sql_elephant);
                pst_elephant.setString(1, rs.getString("id"));
                ResultSet rs_elephant = pst_elephant.executeQuery();
                
                while (rs_elephant.next()) {
                    cmb_id.addItem(rs_elephant.getString("id"));
                }
            } 
            
            conn.close();
        } catch (Exception e) {
            System.out.println("Failiure: " + e);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JComboBox<String> cmb_gender;
    private javax.swing.JComboBox<String> cmb_habitat;
    private javax.swing.JComboBox<String> cmb_id;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_error_message;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_habitat;
    private javax.swing.JLabel lbl_height;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_instructions5;
    private javax.swing.JLabel lbl_instructions6;
    private javax.swing.JLabel lbl_instructions7;
    private javax.swing.JLabel lbl_instructions8;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_weight;
    private javax.swing.JTextField txt_height;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_weight;
    // End of variables declaration//GEN-END:variables
}
