
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mws_a
 */
public class HabitatAlterForm extends javax.swing.JFrame {

    /**
     * Creates new form HabitatAlterForm
     */
    private String rangerId;
    private String wpa;
    private String username;
    private String password;
    
    public HabitatAlterForm(String rangerId, String wpa, String username, String password) {
        initComponents();
        setRangerId(rangerId);
        setWpa(wpa);
        setUsername(username);
        setPassword(password);
       
        populateCmbId();
    }

//    Setters
    public void setRangerId(String rangerId) {
        this.rangerId = rangerId;
    }

    public void setWpa(String wpa) {
        this.wpa = wpa;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    
    
//    Getters
    public String getRangerId() {
        return rangerId;
    }

    public String getWpa() {
        return wpa;
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        txt_latitude = new javax.swing.JTextField();
        lbl_latitude = new javax.swing.JLabel();
        lbl_longitude = new javax.swing.JLabel();
        txt_longitude = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();
        cmb_id = new javax.swing.JComboBox<>();
        lbl_error_message = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        lbl_error_message_1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 400));

        jPanel1.setLayout(null);

        lbl_title.setBackground(new java.awt.Color(33, 37, 41));
        lbl_title.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        lbl_title.setText("Alter Habitat Form");
        lbl_title.setOpaque(true);
        jPanel1.add(lbl_title);
        lbl_title.setBounds(0, 0, 460, 100);

        txt_latitude.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_latitude);
        txt_latitude.setBounds(130, 190, 300, 40);

        lbl_latitude.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_latitude.setText("Latitude");
        jPanel1.add(lbl_latitude);
        lbl_latitude.setBounds(20, 190, 110, 40);

        lbl_longitude.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_longitude.setText("Longitude");
        jPanel1.add(lbl_longitude);
        lbl_longitude.setBounds(20, 240, 110, 40);

        txt_longitude.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_longitude);
        txt_longitude.setBounds(130, 240, 300, 40);

        btn_back.setBackground(new java.awt.Color(33, 37, 41));
        btn_back.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_back.setForeground(new java.awt.Color(248, 249, 250));
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(50, 320, 110, 50);

        btn_edit.setBackground(new java.awt.Color(33, 37, 41));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(248, 249, 250));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit);
        btn_edit.setBounds(190, 320, 110, 50);

        lbl_id.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_id.setText("ID");
        jPanel1.add(lbl_id);
        lbl_id.setBounds(20, 140, 90, 40);

        cmb_id.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmb_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cmb_id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_idItemStateChanged(evt);
            }
        });
        jPanel1.add(cmb_id);
        cmb_id.setBounds(130, 140, 300, 40);

        lbl_error_message.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_error_message.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_error_message);
        lbl_error_message.setBounds(10, 460, 420, 40);

        btn_delete.setBackground(new java.awt.Color(33, 37, 41));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(248, 249, 250));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);
        btn_delete.setBounds(320, 320, 110, 50);

        lbl_error_message_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_error_message_1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_error_message_1);
        lbl_error_message_1.setBounds(10, 420, 420, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        WildlifeRangerDashboard wrd = new WildlifeRangerDashboard(getRangerId(), "xx", "xx", "xx");
        wrd.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void cmb_idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_idItemStateChanged
        // TODO add your handling code here:
        String id = String.valueOf(cmb_id.getSelectedItem());
        String latitude;
        String longitude;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT location FROM habitat WHERE id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, String.valueOf(id));
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String location[] = rs.getString("location").split(",");
                latitude = location[0].replaceAll("\\s", "");;
                longitude = location[1].replaceAll("\\s", "");;
                txt_latitude.setText(latitude);
                txt_longitude.setText(longitude);
            } 
//                System.out.println(rs.getString("location"));

            conn.close();
        } catch (Exception e) {
            lbl_error_message.setText("Failiure: " + e);
        }
        
    }//GEN-LAST:event_cmb_idItemStateChanged

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        lbl_error_message.setText("");
        if ( String.valueOf(cmb_id.getSelectedItem()).equals("Select") ||
                txt_latitude.getText().equals("") || 
                !Validator.isNumber(txt_latitude.getText()) ||
                txt_longitude.getText().equals("") ||
                !Validator.isNumber(txt_longitude.getText()) ) {
            lbl_error_message.setText("Lattitude and longitude are required to add habitat as numbers");
            lbl_error_message_1.setText("and a valid ID should be picked");
        } else { 
            Habitat h = new Habitat();
            h.setId(String.valueOf(cmb_id.getSelectedItem()));
            h.setLocation(txt_latitude.getText() + ", "+ txt_longitude.getText() );
            h.setWpa(getWpa());
            h.edit();
            JOptionPane.showMessageDialog(this, "Habitat successfully Deleted!");
            WildlifeRangerDashboard wrd = new WildlifeRangerDashboard(getRangerId(),getUsername(), getPassword(), "Wildlife Ranger");
            wrd.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        lbl_error_message.setText("");
        if (String.valueOf(cmb_id.getSelectedItem()).equals("Select")) {
            lbl_error_message.setText("Please pick a valid habitad ID");
        } else {
            String id = String.valueOf(cmb_id.getSelectedItem());
            Habitat h = new Habitat();
            h.setId(id);
            h.delete();
            JOptionPane.showMessageDialog(this, "Habitat successfully Deleted!");
            WildlifeRangerDashboard wrd = new WildlifeRangerDashboard(getRangerId(),getUsername(), getPassword(), "Wildlife Ranger");
            wrd.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void populateCmbId() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT id FROM habitat WHERE wpa = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, String.valueOf(getWpa()));
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                cmb_id.addItem(rs.getString("id"));
            } 

            conn.close();
        } catch (Exception e) {
            lbl_error_message.setText("Failiure: " + e);
        }
        
        
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HabitatAlterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HabitatAlterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HabitatAlterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HabitatAlterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HabitatAlterForm("87", "11").setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JComboBox<String> cmb_id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_error_message;
    private javax.swing.JLabel lbl_error_message_1;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_latitude;
    private javax.swing.JLabel lbl_longitude;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_latitude;
    private javax.swing.JTextField txt_longitude;
    // End of variables declaration//GEN-END:variables
}
