/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mws_a
 */
public class LoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form LoginWindow
     */
    int x,y;
    public LoginWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        tbt_pane_login = new javax.swing.JTabbedPane();
        pnl_login = new javax.swing.JPanel();
        lbl_user_sub_heading = new javax.swing.JLabel();
        lbl_username_user = new javax.swing.JLabel();
        txt_username_user = new javax.swing.JTextField();
        lbl_password_user = new javax.swing.JLabel();
        txt_password_user = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        lbl_login_button_user = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_ranger_sub_heading1 = new javax.swing.JLabel();
        lbl_nic_ranger = new javax.swing.JLabel();
        lbl_urrn_ranger = new javax.swing.JLabel();
        txt_password_ranger = new javax.swing.JPasswordField();
        txt_username_ranger = new javax.swing.JTextField();
        lbl_btn_login_ranger = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        pan_icon = new javax.swing.JPanel();
        lbl_wcms_icon = new javax.swing.JLabel();
        lbl_login_verification_message = new javax.swing.JLabel();
        btn_ranger_toggle = new javax.swing.JButton();
        btn_user_toggle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(33, 37, 41));
        jPanel3.setLayout(null);

        tbt_pane_login.setBackground(new java.awt.Color(102, 102, 0));
        tbt_pane_login.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        pnl_login.setBackground(new java.awt.Color(33, 37, 41));

        lbl_user_sub_heading.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_user_sub_heading.setForeground(new java.awt.Color(248, 249, 250));
        lbl_user_sub_heading.setText("User Login");

        lbl_username_user.setBackground(new java.awt.Color(248, 249, 250));
        lbl_username_user.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_username_user.setForeground(new java.awt.Color(248, 249, 250));
        lbl_username_user.setText("Username");

        lbl_password_user.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_password_user.setForeground(new java.awt.Color(248, 249, 250));
        lbl_password_user.setText("Password");

        txt_password_user.setText("jPasswordField1");

        lbl_login_button_user.setBackground(new java.awt.Color(33, 37, 41));
        lbl_login_button_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_login_button_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/btn_login_light.jpg"))); // NOI18N
        lbl_login_button_user.setToolTipText("");
        lbl_login_button_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_login_button_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_login_button_userMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_loginLayout = new javax.swing.GroupLayout(pnl_login);
        pnl_login.setLayout(pnl_loginLayout);
        pnl_loginLayout.setHorizontalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_user_sub_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_loginLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_loginLayout.createSequentialGroup()
                                .addComponent(lbl_login_button_user)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_loginLayout.createSequentialGroup()
                                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_username_user, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_password_user, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_username_user, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_password_user, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(387, Short.MAX_VALUE))
        );
        pnl_loginLayout.setVerticalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_user_sub_heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_username_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_username_user, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_password_user)
                    .addComponent(txt_password_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_loginLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_loginLayout.createSequentialGroup()
                        .addComponent(lbl_login_button_user, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        tbt_pane_login.addTab("tab1", pnl_login);

        jPanel1.setBackground(new java.awt.Color(33, 37, 41));

        lbl_ranger_sub_heading1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbl_ranger_sub_heading1.setForeground(new java.awt.Color(248, 249, 250));
        lbl_ranger_sub_heading1.setText("Ranger Login");

        lbl_nic_ranger.setBackground(new java.awt.Color(248, 249, 250));
        lbl_nic_ranger.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_nic_ranger.setForeground(new java.awt.Color(248, 249, 250));
        lbl_nic_ranger.setText("Username");

        lbl_urrn_ranger.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_urrn_ranger.setForeground(new java.awt.Color(248, 249, 250));
        lbl_urrn_ranger.setText("Password");

        txt_password_ranger.setText("jPasswordField1");

        lbl_btn_login_ranger.setBackground(new java.awt.Color(33, 37, 41));
        lbl_btn_login_ranger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/btn_login_light.jpg"))); // NOI18N
        lbl_btn_login_ranger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_btn_login_rangerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_btn_login_rangerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ranger_sub_heading1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_nic_ranger, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_urrn_ranger, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_username_ranger, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_password_ranger, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbl_btn_login_ranger, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(398, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_ranger_sub_heading1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_username_ranger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nic_ranger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_urrn_ranger)
                    .addComponent(txt_password_ranger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(lbl_btn_login_ranger)
                .addGap(52, 52, 52))
        );

        tbt_pane_login.addTab("tab2", jPanel1);

        jPanel3.add(tbt_pane_login);
        tbt_pane_login.setBounds(370, 90, 729, 230);

        lbl_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_title.setText("Welcome to the Wildlife Concervation Management System of Sri Lanka");
        jPanel3.add(lbl_title);
        lbl_title.setBounds(20, 30, 812, 32);

        pan_icon.setBackground(new java.awt.Color(33, 37, 41));

        lbl_wcms_icon.setBackground(new java.awt.Color(0, 0, 0));
        lbl_wcms_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_wcms_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wcms_icon_light.jpeg"))); // NOI18N
        lbl_wcms_icon.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout pan_iconLayout = new javax.swing.GroupLayout(pan_icon);
        pan_icon.setLayout(pan_iconLayout);
        pan_iconLayout.setHorizontalGroup(
            pan_iconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_iconLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_wcms_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pan_iconLayout.setVerticalGroup(
            pan_iconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_iconLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_wcms_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel3.add(pan_icon);
        pan_icon.setBounds(20, 80, 310, 320);

        lbl_login_verification_message.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_login_verification_message.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(lbl_login_verification_message);
        lbl_login_verification_message.setBounds(370, 330, 470, 30);

        btn_ranger_toggle.setBackground(new java.awt.Color(33, 37, 41));
        btn_ranger_toggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/btn_ranger_light.jpg"))); // NOI18N
        btn_ranger_toggle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ranger_toggleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ranger_toggleMouseExited(evt);
            }
        });
        btn_ranger_toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ranger_toggleActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ranger_toggle);
        btn_ranger_toggle.setBounds(430, 390, 70, 40);

        btn_user_toggle.setBackground(new java.awt.Color(33, 37, 41));
        btn_user_toggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/btn_user_light.jpg"))); // NOI18N
        btn_user_toggle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_user_toggleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_user_toggleMouseExited(evt);
            }
        });
        btn_user_toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_user_toggleActionPerformed(evt);
            }
        });
        jPanel3.add(btn_user_toggle);
        btn_user_toggle.setBounds(370, 390, 50, 40);

        jPanel2.setBackground(new java.awt.Color(33, 37, 41));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(33, 37, 41));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\mws_a\\Downloads\\Pictures\\btn_close.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 840, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(0, 0, 860, 30);

        filler1.setBackground(new java.awt.Color(248, 249, 250));
        jPanel3.add(filler1);
        filler1.setBounds(330, 90, 10, 340);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_login_button_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_login_button_userMouseEntered
        // TODO add your handling code here:        
        lbl_login_button_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/btn_login_dark.jpg")));
    }//GEN-LAST:event_lbl_login_button_userMouseEntered

    private void lbl_login_button_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_login_button_userMouseExited
        // TODO add your handling code here:
        lbl_login_button_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/btn_login_light.jpg")));
    }//GEN-LAST:event_lbl_login_button_userMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btn_user_toggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_user_toggleActionPerformed
        // TODO add your handling code here:
        tbt_pane_login.setSelectedIndex(0);
    }//GEN-LAST:event_btn_user_toggleActionPerformed

    private void btn_ranger_toggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ranger_toggleActionPerformed
        // TODO add your handling code here:
        tbt_pane_login.setSelectedIndex(1);
    }//GEN-LAST:event_btn_ranger_toggleActionPerformed

    private void lbl_btn_login_rangerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_login_rangerMouseEntered
        // TODO add your handling code here:
        lbl_login_button_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/btn_login_dark.jpg")));
    }//GEN-LAST:event_lbl_btn_login_rangerMouseEntered

    private void btn_user_toggleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_user_toggleMouseEntered
        // TODO add your handling code here:
        btn_user_toggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/btn_user_dark.jpg")));
    }//GEN-LAST:event_btn_user_toggleMouseEntered

    private void btn_user_toggleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_user_toggleMouseExited
        // TODO add your handling code here:
        btn_user_toggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/btn_user_light.jpg")));
    }//GEN-LAST:event_btn_user_toggleMouseExited

    private void lbl_btn_login_rangerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_login_rangerMouseExited
        // TODO add your handling code here:
        btn_user_toggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/btn_login_light.jpg")));
    }//GEN-LAST:event_lbl_btn_login_rangerMouseExited

    private void btn_ranger_toggleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ranger_toggleMouseEntered
        // TODO add your handling code here:
        btn_ranger_toggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/btn_ranger_dark.jpg")));
    }//GEN-LAST:event_btn_ranger_toggleMouseEntered

    private void btn_ranger_toggleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ranger_toggleMouseExited
        // TODO add your handling code here:
        btn_ranger_toggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/btn_ranger_light.jpg")));
    }//GEN-LAST:event_btn_ranger_toggleMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ranger_toggle;
    private javax.swing.JButton btn_user_toggle;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_btn_login_ranger;
    private javax.swing.JLabel lbl_login_button_user;
    private javax.swing.JLabel lbl_login_verification_message;
    private javax.swing.JLabel lbl_nic_ranger;
    private javax.swing.JLabel lbl_password_user;
    private javax.swing.JLabel lbl_ranger_sub_heading1;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_urrn_ranger;
    private javax.swing.JLabel lbl_user_sub_heading;
    private javax.swing.JLabel lbl_username_user;
    private javax.swing.JLabel lbl_wcms_icon;
    private javax.swing.JPanel pan_icon;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JTabbedPane tbt_pane_login;
    private javax.swing.JPasswordField txt_password_ranger;
    private javax.swing.JPasswordField txt_password_user;
    private javax.swing.JTextField txt_username_ranger;
    private javax.swing.JTextField txt_username_user;
    // End of variables declaration//GEN-END:variables
}
