
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mws_a
 */
public class PersonalInformationChangeForm extends javax.swing.JFrame {

    /**
     * Creates new form PersonalInformationChangeForm
     */
    private String id;
    private String first_name;
    private String last_name;
    private String username;
    private String address;
    private LocalDate dob;
    private String email;
    private String nic;    
    private String password;
    private String role;
    
    public PersonalInformationChangeForm(String id, String role) {
        initComponents();
        setId(id);
        setRole(role);
        populateForm(id);
        
        System.out.println("Role: " + getRole());
//        lbl_error_message.setText(getId());
    }
    
//    Setters

    public void setId(String id) {
        this.id = id;
    }

    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }
    
    
    public void setUsername(String username) {
        this.username = username;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public void setDob(LocalDate dob) {
        this.dob = dob;
    }
    
    
    public void setEmail(String email) {
        this.email = email;
    }

    public void setNic(String nic) {
        this.nic = nic;
    }
     

    public void setPassword(String password) {
        this.password = password;
    }

    public void setRole(String role) {
        this.role = role;
    }
    
    
    
    
    
//    Getters

    public String getId() {
        return id;
    }

    public String getFirst_name() {
        return first_name;
    }

    public String getLast_name() {
        return last_name;
    }
    
    public String getUsername() {
        return username;
    }

    public String getAddress() {
        return address;
    }

    public LocalDate getDob() {
        return dob;
    }

    public String getEmail() {
        return email;
    }

    public String getNic() {
        return nic;
    }
    
    public String getPassword() {
        return password;
    }

    public String getRole() {
        return role;
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_username = new javax.swing.JTextField();
        txt_old_password = new javax.swing.JPasswordField();
        txt_new_password = new javax.swing.JPasswordField();
        lbl_username = new javax.swing.JLabel();
        lbl_old_password = new javax.swing.JLabel();
        lbl_new_password = new javax.swing.JLabel();
        lbl_error_message = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        pnl_information = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_username);
        txt_username.setBounds(140, 150, 190, 40);

        txt_old_password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_old_password);
        txt_old_password.setBounds(140, 200, 190, 40);

        txt_new_password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txt_new_password);
        txt_new_password.setBounds(140, 250, 190, 40);

        lbl_username.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_username.setText("Username");
        jPanel1.add(lbl_username);
        lbl_username.setBounds(20, 150, 120, 40);

        lbl_old_password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_old_password.setText("Old Password");
        jPanel1.add(lbl_old_password);
        lbl_old_password.setBounds(10, 200, 130, 40);

        lbl_new_password.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_new_password.setText("New Password");
        jPanel1.add(lbl_new_password);
        lbl_new_password.setBounds(10, 250, 130, 40);

        lbl_error_message.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_error_message);
        lbl_error_message.setBounds(10, 390, 820, 50);

        lbl_title.setBackground(new java.awt.Color(33, 37, 41));
        lbl_title.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        lbl_title.setText("Edit Personal Information");
        lbl_title.setOpaque(true);
        jPanel1.add(lbl_title);
        lbl_title.setBounds(0, 0, 850, 100);

        btn_save.setBackground(new java.awt.Color(33, 37, 41));
        btn_save.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_save.setForeground(new java.awt.Color(248, 249, 250));
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save);
        btn_save.setBounds(240, 320, 90, 40);

        btn_close.setBackground(new java.awt.Color(33, 37, 41));
        btn_close.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_close.setForeground(new java.awt.Color(248, 249, 250));
        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_close);
        btn_close.setBounds(140, 320, 90, 40);

        pnl_information.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instructions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(33, 37, 41))); // NOI18N

        jLabel1.setText("Old pass word field must match your existing password");

        jLabel2.setText("Only enter new password if you want to change your password otherwise leave it empty");

        jLabel3.setText("Your new password should at least be minimum of 6 character length");

        jLabel4.setText("The username field cannot be empty");

        javax.swing.GroupLayout pnl_informationLayout = new javax.swing.GroupLayout(pnl_information);
        pnl_information.setLayout(pnl_informationLayout);
        pnl_informationLayout.setHorizontalGroup(
            pnl_informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_informationLayout.createSequentialGroup()
                .addGroup(pnl_informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_informationLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_informationLayout.createSequentialGroup()
                        .addGroup(pnl_informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_informationLayout.setVerticalGroup(
            pnl_informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_informationLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(73, 73, 73))
        );

        jPanel1.add(pnl_information);
        pnl_information.setBounds(360, 130, 480, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateForm(String id) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT first_name, last_name, username, address, dob, email, nic, password, role FROM user WHERE id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, String.valueOf(getId()));
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                DepartmentOfficer do1 = new DepartmentOfficer();
                setId(id);
                setFirst_name(rs.getString("first_name"));
                setLast_name(rs.getString("last_name"));
                setUsername(rs.getString("username"));
                setAddress(rs.getString("address"));
                System.out.println(rs.getString("username"));
                System.out.println(rs.getString("password"));
                
                Date dob = rs.getDate("dob");
                SimpleDateFormat formatter = new SimpleDateFormat("YYYY-MM-d");
                String dob_mysql_date_string = formatter.format(dob);
                int dob_year = Integer.parseInt(dob_mysql_date_string.substring(0,4));
                int dob_month = Integer.parseInt(dob_mysql_date_string.substring(5,7));
                int dob_day = Integer.parseInt(dob_mysql_date_string.substring(8));
                setDob(LocalDate.of(dob_year, dob_month, dob_day));
                
                setEmail(rs.getString("email"));
                setNic(rs.getString("nic"));
                setPassword(rs.getString("password"));
                setRole(rs.getString("role"));
                txt_username.setText(String.valueOf(getUsername()));
                setUsername(do1.getUsername());
//                setPassword(do1.getPassword());
//                System.out.println(do1.getDate_of_birth());
            } 
            conn.close();
        } catch (Exception e) {
            System.out.println("Failiure: " + e);
        }
    }
    
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        lbl_error_message.setText("");
        if (txt_username.getText().equals("")) {
            lbl_error_message.setText("The username field cannot be empty!");
        } else {
            if (Validator.validatePassword(getId(), txt_old_password.getText())) {
                DepartmentOfficer do1 = new DepartmentOfficer();
                do1.setId(getId());
                do1.setFirst_name(getFirst_name());
                do1.setLast_name(getLast_name());
                do1.setUsername(txt_username.getText());
                do1.setAddress(getAddress());
                do1.setNic(getNic());


    //            Date dob = rs.getDate("dob");
    //            SimpleDateFormat formatter = new SimpleDateFormat("YYYY-MM-d");
    //            String dob_mysql_date_string = formatter.format(dob);
    //            int dob_year = Integer.parseInt(dob_mysql_date_string.substring(0,4));
    //            int dob_month = Integer.parseInt(dob_mysql_date_string.substring(5,7));
    //            int dob_day = Integer.parseInt(dob_mysql_date_string.substring(8));
                do1.setDate_of_birth(getDob());

                do1.setEmail(getEmail());
                do1.setRole(getRole());
                if (txt_new_password.getText().equals("") || txt_new_password.getText() == null) {
                    do1.setPassword(getPassword());
                    System.out.println("jok" + this.getPassword());
                    do1.edit();
                    JOptionPane.showMessageDialog(this, "Your personal information successfully changed!");
                    goBack();
                } else if (txt_new_password.getText().length() < 6) {
                    lbl_error_message.setText("Password not long enough");                
                    do1.setPassword(getPassword());
                } else {
                    do1.setPassword(txt_new_password.getText());
                    do1.edit();
                    JOptionPane.showMessageDialog(this, "Your personal information successfully changed!");
                    goBack();
                }


            } else {
                lbl_error_message.setText("Password Don't match");
            }        
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        goBack();
        
    }//GEN-LAST:event_btn_closeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PersonalInformationChangeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PersonalInformationChangeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PersonalInformationChangeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PersonalInformationChangeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PersonalInformationChangeForm().setVisible(true);
//            }
//        });
//    }
    
    private void goBack () {        
        if (getRole().equals("Department Officer")) {
            DepartmentOfficerDashboard dod = new DepartmentOfficerDashboard(getId(), "xx", "xx", "xx");
            dod.setVisible(true);
            dispose();            
        } else if (getRole().equals("Director General")) {
            DirectorGeneralDashBoard dg = new DirectorGeneralDashBoard(getId(), getUsername(), getPassword(), "Director General");
            dg.setVisible(true);
            dispose();            
        } else if (getRole().equals("Wildlife Ranger")) {
            WildlifeRangerDashboard wr = new WildlifeRangerDashboard(getId(), "xx", "xx", "xx");
            wr.setVisible(true);
            dispose();            
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_error_message;
    private javax.swing.JLabel lbl_new_password;
    private javax.swing.JLabel lbl_old_password;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pnl_information;
    private javax.swing.JPasswordField txt_new_password;
    private javax.swing.JPasswordField txt_old_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
