
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mws_a
 */
public class PopulationTable extends javax.swing.JFrame {

    /**
     * Creates new form PopulationTable
     */
    private String wpa;
    public PopulationTable(String WPA) {
        initComponents();
        setWpa(WPA);
        lbl_test.setText("Wildlife Protected Area ID: " + getWpa());
        populatePopulationTable();
    }
    
//    Setters

    public void setWpa(String wpa) {
        this.wpa = wpa;
    }
    
//    Getters

    public String getWpa() {
        return wpa;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        sct_pnl_population_table = new javax.swing.JScrollPane();
        tbl_population = new javax.swing.JTable();
        lbl_test = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(248, 249, 250));
        jPanel1.setLayout(null);

        lbl_title.setBackground(new java.awt.Color(33, 37, 31));
        lbl_title.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        lbl_title.setText("Population Table");
        lbl_title.setOpaque(true);
        jPanel1.add(lbl_title);
        lbl_title.setBounds(0, 0, 800, 100);

        sct_pnl_population_table.setBackground(new java.awt.Color(248, 249, 250));

        tbl_population.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Population"
            }
        ));
        tbl_population.setRowHeight(18);
        tbl_population.setRowMargin(2);
        tbl_population.setSelectionBackground(new java.awt.Color(33, 37, 41));
        tbl_population.setSelectionForeground(new java.awt.Color(248, 249, 250));
        sct_pnl_population_table.setViewportView(tbl_population);

        jPanel1.add(sct_pnl_population_table);
        sct_pnl_population_table.setBounds(10, 150, 770, 340);

        lbl_test.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_test.setForeground(new java.awt.Color(33, 37, 41));
        lbl_test.setText("WPA ID");
        jPanel1.add(lbl_test);
        lbl_test.setBounds(10, 110, 170, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PopulationTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PopulationTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PopulationTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PopulationTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PopulationTable().setVisible(true);
//            }
//        });
//    }
    
    private void populatePopulationTable () {
        try {
                   Class.forName("com.mysql.cj.jdbc.Driver"); 
                   Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
                   String sql = "SELECT id, date, population FROM elephantpopulation WHERE wpa = ?";

                   PreparedStatement pst = conn.prepareStatement(sql);
                   pst.setString(1, getWpa());
   //                pst.setString(2, String.valueOf(txt_password.getText()));
                   ResultSet rs = pst.executeQuery();

                   while (rs.next()) {

                       String id = rs.getString("id");
                       String date = rs.getString("date");
                       String population = rs.getString("population");
                       
                       String population_table_raw[] = {id, date, population};
                       DefaultTableModel population_table = (DefaultTableModel)tbl_population.getModel();
                       population_table.addRow(population_table_raw);

                   } 
                   conn.close();
           } catch (Exception e) {
               System.out.println("Failiure: " + e);
           }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_test;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JScrollPane sct_pnl_population_table;
    private javax.swing.JTable tbl_population;
    // End of variables declaration//GEN-END:variables
}
