
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mws_a
 */
public class SystemAdministratorDashboard extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdministratorDashboard
     */
    
    private String username = "Admin"; 
    private String password = "cypher";
    
    public SystemAdministratorDashboard(String username, String password) {
        initComponents();
//        setUsername(username);
//        setPassword(password);
        populateUserTable();
        
    }

//    Other methods
    
    private void populateUserTable () {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT id, first_name, last_name, address, dob, email, role, registered_date FROM user";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String id = rs.getString("id");
                String fn = rs.getString("first_name");
                String ln = rs.getString("last_name");
                String ad = rs.getString("address");
                String d = rs.getString("dob");
                String e = rs.getString("email");
                String r = rs.getString("role");
                String rd = rs.getString("registered_date");

                String user_info[] = {id,fn,ln,ad, e, d, r, rd};
                DefaultTableModel user_table = (DefaultTableModel)tbl_user.getModel();
                user_table.addRow(user_info);
//                String sql_user = "SELECT id, first_name, last_name, username, address, dob, email, nic, registered_date FROM user WHERE id = ?" ;
//                PreparedStatement pst_user = conn.prepareStatement(sql_user);
//                pst_user.setString(1, String.valueOf(rs.getString("user")));
//                ResultSet rs_user = pst_user.executeQuery();
//
//                if (rs_user.next()) {
//                    String id = rs_user.getString("id");
//                    String fn = rs_user.getString("first_name");
//                    String ln = rs_user.getString("last_name");
//                    String ad = rs_user.getString("address");
//                    String d = rs_user.getString("dob");
//                    String e = rs_user.getString("email");
//                    String n = rs_user.getString("nic");
//                    String rd = rs_user.getString("registered_date");
//                    String w = rs.getString("wpa");
//
//                    String ranger_info[] = {id,fn,ln,ad, e, n, w, d, rd};
//                    DefaultTableModel ranger_table = (DefaultTableModel)tbl_ranger.getModel();
//                    ranger_table.addRow(ranger_info);
//
//                } else {
//                    System.out.println("Wrong id");
//                }               




            } 
            conn.close();
        } catch (Exception e) {
            System.out.println("Failiure: " + e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_welcome_message = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        lbl_title = new javax.swing.JLabel();
        pnl_user_operations = new javax.swing.JPanel();
        btn_add_department_officer = new javax.swing.JButton();
        btn_alter_department_officer = new javax.swing.JButton();
        btn_edit_director_general = new javax.swing.JButton();
        scr_pnl_user_table = new javax.swing.JScrollPane();
        tbl_user = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 249, 250));
        jPanel1.setLayout(null);

        lbl_welcome_message.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_welcome_message.setText("Welcome Administrator");
        jPanel1.add(lbl_welcome_message);
        lbl_welcome_message.setBounds(10, 130, 200, 33);

        btn_logout.setBackground(new java.awt.Color(248, 249, 250));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(33, 37, 41));
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout);
        btn_logout.setBounds(980, 30, 110, 50);

        lbl_title.setBackground(new java.awt.Color(33, 37, 41));
        lbl_title.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(248, 249, 250));
        lbl_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        lbl_title.setText("System Administrator Dashboard");
        lbl_title.setOpaque(true);
        jPanel1.add(lbl_title);
        lbl_title.setBounds(-8, -7, 1120, 100);

        pnl_user_operations.setBackground(new java.awt.Color(248, 249, 250));
        pnl_user_operations.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Operations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16), new java.awt.Color(33, 37, 41))); // NOI18N
        pnl_user_operations.setLayout(null);

        btn_add_department_officer.setBackground(new java.awt.Color(33, 37, 41));
        btn_add_department_officer.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_add_department_officer.setForeground(new java.awt.Color(248, 249, 250));
        btn_add_department_officer.setText("Add Department Officer");
        btn_add_department_officer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_department_officerActionPerformed(evt);
            }
        });
        pnl_user_operations.add(btn_add_department_officer);
        btn_add_department_officer.setBounds(390, 40, 220, 50);

        btn_alter_department_officer.setBackground(new java.awt.Color(33, 37, 41));
        btn_alter_department_officer.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_alter_department_officer.setForeground(new java.awt.Color(248, 249, 250));
        btn_alter_department_officer.setText("Alter Department Officer");
        btn_alter_department_officer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alter_department_officerActionPerformed(evt);
            }
        });
        pnl_user_operations.add(btn_alter_department_officer);
        btn_alter_department_officer.setBounds(620, 40, 230, 50);

        btn_edit_director_general.setBackground(new java.awt.Color(33, 37, 41));
        btn_edit_director_general.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_edit_director_general.setForeground(new java.awt.Color(248, 249, 250));
        btn_edit_director_general.setText("Edit Director General");
        btn_edit_director_general.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_director_generalActionPerformed(evt);
            }
        });
        pnl_user_operations.add(btn_edit_director_general);
        btn_edit_director_general.setBounds(860, 40, 210, 50);

        tbl_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Address", "Email", "Date of Birth", "Role", "Registered Date"
            }
        ));
        scr_pnl_user_table.setViewportView(tbl_user);

        pnl_user_operations.add(scr_pnl_user_table);
        scr_pnl_user_table.setBounds(30, 110, 1040, 250);

        jPanel1.add(pnl_user_operations);
        pnl_user_operations.setBounds(10, 250, 1090, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_department_officerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_department_officerActionPerformed
        // TODO add your handling code here:
        AddDepartmentOfficer waf = new AddDepartmentOfficer(getUsername(), getPassword());
        waf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_add_department_officerActionPerformed

    private void btn_alter_department_officerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alter_department_officerActionPerformed
        // TODO add your handling code here:
        AlterDepartmentOfficerForm adf = new AlterDepartmentOfficerForm(getUsername(), getPassword());
        adf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_alter_department_officerActionPerformed

    private void btn_edit_director_generalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_director_generalActionPerformed
        // TODO add your handling code here:
        EditDirectorGeneral ed = new EditDirectorGeneral(getUsername(), getPassword());
        ed.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_edit_director_generalActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        LoginPanel lp = new LoginPanel();
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    
//    Setters
    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    

//   getters
    public String getUsername() {
        return this.username;
    }
    
    public String getPassword() {
        return this.password;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_department_officer;
    private javax.swing.JButton btn_alter_department_officer;
    private javax.swing.JButton btn_edit_director_general;
    private javax.swing.JButton btn_logout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_welcome_message;
    private javax.swing.JPanel pnl_user_operations;
    private javax.swing.JScrollPane scr_pnl_user_table;
    private javax.swing.JTable tbl_user;
    // End of variables declaration//GEN-END:variables
}
