
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mws_a
 */
public class WildlifeRangerEditDeleteForm extends javax.swing.JFrame {

    /**
     * Creates new form WildlifeRangerEditDeleteForm
     */
    private DepartmentOfficer do1;
    private String id;
    public WildlifeRangerEditDeleteForm(String id) {
        initComponents();
        setId(id);
        do1 = initiateDepartmentOfficer(getId());
        populateCmbId();
        populateCmbWpa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        txt_first_name = new javax.swing.JTextField();
        txt_last_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        lbl_dob = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        dtch_dob = new com.toedter.calendar.JDateChooser();
        lbl_wpa = new javax.swing.JLabel();
        txt_nic = new javax.swing.JTextField();
        lbl_nic = new javax.swing.JLabel();
        cmb_wpa = new javax.swing.JComboBox<>();
        lbl_address = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        lbl_error_message = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cmb_id = new javax.swing.JComboBox<>();
        lbl_id = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_instructions5 = new javax.swing.JLabel();
        lbl_instructions6 = new javax.swing.JLabel();
        lbl_instructions7 = new javax.swing.JLabel();
        lbl_instructions8 = new javax.swing.JLabel();
        lbl_instructions9 = new javax.swing.JLabel();
        lbl_instructions = new javax.swing.JLabel();
        lbl_instructions1 = new javax.swing.JLabel();
        lbl_instructions10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 249, 250));
        jPanel1.setLayout(null);

        lbl_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_name.setText("Name ");
        jPanel1.add(lbl_name);
        lbl_name.setBounds(10, 190, 70, 22);

        txt_first_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_first_name.setText("First Name");
        txt_first_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_first_nameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_first_name);
        txt_first_name.setBounds(110, 190, 160, 28);

        txt_last_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_last_name.setText("Last Name");
        jPanel1.add(txt_last_name);
        txt_last_name.setBounds(280, 190, 160, 28);

        jLabel1.setBackground(new java.awt.Color(33, 37, 41));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 249, 250));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jLabel1.setText("Alter Wildlifer Ranger");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, 0, 1000, 100);

        txt_address.setColumns(20);
        txt_address.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_address.setRows(5);
        jScrollPane1.setViewportView(txt_address);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(110, 240, 330, 116);

        lbl_dob.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_dob.setText("Date of Birth");
        jPanel1.add(lbl_dob);
        lbl_dob.setBounds(10, 380, 120, 30);

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel1.add(txt_email);
        txt_email.setBounds(110, 430, 320, 28);

        lbl_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_email.setText("Email");
        jPanel1.add(lbl_email);
        lbl_email.setBounds(10, 430, 100, 30);

        dtch_dob.setDateFormatString("yyyy-MM-dd");
        dtch_dob.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(dtch_dob);
        dtch_dob.setBounds(110, 380, 200, 30);

        lbl_wpa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_wpa.setText("Wildlife Protected Area");
        jPanel1.add(lbl_wpa);
        lbl_wpa.setBounds(10, 540, 180, 22);

        txt_nic.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nicActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nic);
        txt_nic.setBounds(110, 480, 320, 28);

        lbl_nic.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_nic.setText("NIC");
        jPanel1.add(lbl_nic);
        lbl_nic.setBounds(10, 480, 100, 30);

        cmb_wpa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmb_wpa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cmb_wpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_wpaActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_wpa);
        cmb_wpa.setBounds(210, 540, 200, 28);

        lbl_address.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_address.setText("Address");
        jPanel1.add(lbl_address);
        lbl_address.setBounds(10, 280, 70, 20);

        btn_close.setBackground(new java.awt.Color(33, 37, 41));
        btn_close.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_close.setForeground(new java.awt.Color(248, 249, 250));
        btn_close.setText("Back");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_close);
        btn_close.setBounds(30, 600, 90, 50);

        btn_edit.setBackground(new java.awt.Color(33, 37, 41));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(248, 249, 250));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit);
        btn_edit.setBounds(330, 600, 90, 50);

        btn_clear.setBackground(new java.awt.Color(33, 37, 41));
        btn_clear.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(248, 249, 250));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear);
        btn_clear.setBounds(130, 600, 90, 50);

        lbl_error_message.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_error_message.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_error_message);
        lbl_error_message.setBounds(20, 670, 950, 40);

        jButton1.setBackground(new java.awt.Color(33, 37, 41));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(248, 249, 250));
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(230, 600, 90, 50);

        cmb_id.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmb_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cmb_id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_idItemStateChanged(evt);
            }
        });
        jPanel1.add(cmb_id);
        cmb_id.setBounds(110, 130, 120, 30);

        lbl_id.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_id.setText("ID");
        jPanel1.add(lbl_id);
        lbl_id.setBounds(10, 130, 80, 30);

        jPanel2.setBackground(new java.awt.Color(248, 249, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instructions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(33, 37, 41))); // NOI18N

        lbl_instructions5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_instructions5.setText("Make sure that you filled all fields.");
        lbl_instructions5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_instructions6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_instructions6.setText("First and last names should be something other than First Name and Last Name.");
        lbl_instructions6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_instructions7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_instructions7.setText("Email should be correctly formatted and cannot exist in WCMS database.");
        lbl_instructions7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_instructions8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_instructions8.setText("NIC should not exist in the WCMS either.");
        lbl_instructions8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_instructions9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_instructions9.setText("A valid wildlife protected area must be selected.");
        lbl_instructions9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_instructions.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instructions.setText("When you are altering existig ranger information:");
        lbl_instructions.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_instructions1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_instructions1.setText("When you are deleting a ranger");
        lbl_instructions1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_instructions10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_instructions10.setText("Choose a valid wildlife ranger id and it cannot be in select");
        lbl_instructions10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_instructions5, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_instructions6, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_instructions7, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_instructions8, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_instructions9, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_instructions1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_instructions10, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbl_instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_instructions5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbl_instructions6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbl_instructions7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbl_instructions8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbl_instructions9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lbl_instructions1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_instructions10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(490, 130, 480, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//Setters
    
    public void setId(String id) {
        this.id = id;
    }
    
//    Getters
    public String getId() {
        return id;
    }
    
    
    private void txt_first_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_first_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_first_nameActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nicActionPerformed

    private void cmb_wpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_wpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_wpaActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        DepartmentOfficerDashboard dod = new DepartmentOfficerDashboard(getId(), "xxx", "xx", "xx");
        dod.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        lbl_error_message.setText("");
//
        if (txt_first_name.getText().equals("First Name") ||
            txt_first_name.getText().equals("") ||
            txt_last_name.getText().equals("Last Name") ||
            txt_last_name.getText().equals("") ||
            txt_address.getText().equals("") ||
            dtch_dob.getDate() == null ||
            txt_email.getText().equals("") ||
            Validator.validateEmailFormat(String.valueOf(txt_email.getText())) == false ||
            txt_nic.getText().equals("") ||
            String.valueOf(cmb_wpa.getSelectedItem()).equals("Select")
        ) {
            lbl_error_message.setText("You must enter valid values in the fields!");
        } else {
            Date dob = dtch_dob.getDate();
            SimpleDateFormat formatter = new SimpleDateFormat("YYYY-MM-d");
            String dob_mysql_date_string = formatter.format(dob);
            System.out.println(dob_mysql_date_string); 
            int dob_year = Integer.parseInt(dob_mysql_date_string.substring(0,4));
            int dob_month = Integer.parseInt(dob_mysql_date_string.substring(5,7));
            int dob_day = Integer.parseInt(dob_mysql_date_string.substring(8));
            
            System.out.println(dob_year);
            System.out.println(dob_month);
            System.out.println(dob_day);
            do1.editRanger(String.valueOf(cmb_id.getSelectedItem()),
                    txt_first_name.getText(),
                    txt_last_name.getText(),
                    txt_address.getText(),
                    LocalDate.of(dob_year, dob_month, dob_day),
                    txt_email.getText(),
                    txt_nic.getText(),
                    setUpWpaValue(String.valueOf(cmb_wpa.getSelectedItem())));
            lbl_error_message.setText("Edit Successful!");
            emptyFields();
            DepartmentOfficerDashboard dod = new DepartmentOfficerDashboard(getId(), "xx", "xx", "xx");
            dod.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        cmb_id.setSelectedIndex(0);
        txt_first_name.setText("First Name");
        txt_last_name.setText("Last Name");
        txt_address.setText("");
        dtch_dob.setDate(null);
        txt_email.setText("");
        txt_nic.setText("");
        cmb_wpa.setSelectedIndex(0);
        lbl_error_message.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void cmb_idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_idItemStateChanged
        // TODO add your handling code here:
//        lbl_error_message.setText(String.valueOf(cmb_id.getSelectedItem()));
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT first_name, last_name, address, dob, email, nic FROM user WHERE id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, String.valueOf(cmb_id.getSelectedItem()));
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_first_name.setText(rs.getString("first_name"));
                txt_last_name.setText(rs.getString("last_name"));
                txt_address.setText(rs.getString("address"));
//                Setting up date of birth
                String dateValue = rs.getString("dob"); // What ever column
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
                dtch_dob.setDate(date);
                txt_email.setText(rs.getString("email"));
                txt_nic.setText(rs.getString("nic"));
            }             
            
                
            String sql_wr = "SELECT wpa FROM wildliferanger WHERE user = ?";
            PreparedStatement pst_wr = conn.prepareStatement(sql_wr);                
            pst_wr.setString(1, String.valueOf(String.valueOf(cmb_id.getSelectedItem())));            
            ResultSet rs_wr = pst_wr.executeQuery();
            
            if (rs_wr.next()) {
                String sql_wpa = "SELECT name FROM wildlifeprotectedarea WHERE id = ?";
                PreparedStatement pst_wpa = conn.prepareStatement(sql_wpa);                
                pst_wpa.setString(1, String.valueOf(String.valueOf(rs_wr.getString("wpa"))));            
                ResultSet rs_wpa = pst_wpa.executeQuery();
                
                if (rs_wpa.next()) {
                    cmb_wpa.getModel().setSelectedItem(rs_wpa.getString("name"));
                    
                }
            }

            conn.close();
        } catch (Exception e) {
            lbl_error_message.setText("Failiure: " + e);
            System.out.println("Failiure: " + e);
        }
    }//GEN-LAST:event_cmb_idItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        do1.deleteRanger(String.valueOf(cmb_id.getSelectedItem()));
        lbl_error_message.setText("Delet Succesfully!");
        emptyFields();
        DepartmentOfficerDashboard dod = new DepartmentOfficerDashboard(getId(), "xx", "xx", "xx");
        dod.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void populateCmbId() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT user FROM wildliferanger WHERE department_officer = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, String.valueOf(getId()));
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                cmb_id.addItem(rs.getString("user"));
            } 

            conn.close();
        } catch (Exception e) {
            lbl_error_message.setText("Failiure: " + e);
        }
    }
    
    private void populateCmbWpa() {
//        This method will add values of wpa that comes under this department officer to the combo box in the form
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
            String sql = "SELECT name FROM wildlifeprotectedarea WHERE department_officer = ?";
//            SELECT column1, column2, ...
//FROM table_name;
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, String.valueOf(getId()));
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                cmb_wpa.addItem(rs.getString("name"));
            } 

            conn.close();
        } catch (Exception e) {
            lbl_error_message.setText("Failiure: " + e);
        }
    
    }
    
    private DepartmentOfficer initiateDepartmentOfficer (String id) {
        DepartmentOfficer do1 = new DepartmentOfficer();
        do1.setId(id);
        return do1;
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(WildlifeRangerEditDeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(WildlifeRangerEditDeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(WildlifeRangerEditDeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(WildlifeRangerEditDeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new WildlifeRangerEditDeleteForm().setVisible(true);
//            }
//        });
//    }
    
    private String setUpWpaValue (String wpa_name) {
        String wpa_id;
        try {
                Class.forName("com.mysql.cj.jdbc.Driver"); 
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/wcms","wcms","e3H$l5A@eN^p7T&");
                String sql = "SELECT id FROM wildlifeprotectedarea WHERE name = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, wpa_name);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    wpa_id = rs.getString("id");
                } else {
                wpa_id = "No WPAs matches that name";
                }
                 
                
                conn.close();
            } catch (Exception e) {
                wpa_id = "Failiure: " + e;
            }
        return wpa_id;
    }
    
    private void emptyFields () {
        cmb_id.setSelectedIndex(0);
        txt_first_name.setText("First Name");
        txt_last_name.setText("Last Name");
        txt_address.setText("");
        dtch_dob.setDate(null);
        txt_email.setText("");
        txt_nic.setText("");
        cmb_wpa.setSelectedIndex(0);
        lbl_error_message.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_edit;
    private javax.swing.JComboBox<String> cmb_id;
    private javax.swing.JComboBox<String> cmb_wpa;
    private com.toedter.calendar.JDateChooser dtch_dob;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_dob;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_error_message;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_instructions;
    private javax.swing.JLabel lbl_instructions1;
    private javax.swing.JLabel lbl_instructions10;
    private javax.swing.JLabel lbl_instructions5;
    private javax.swing.JLabel lbl_instructions6;
    private javax.swing.JLabel lbl_instructions7;
    private javax.swing.JLabel lbl_instructions8;
    private javax.swing.JLabel lbl_instructions9;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_nic;
    private javax.swing.JLabel lbl_wpa;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_first_name;
    private javax.swing.JTextField txt_last_name;
    private javax.swing.JTextField txt_nic;
    // End of variables declaration//GEN-END:variables
}
